<!DOCTYPE html>
<html lang="de"><head>
<link href="../assets/dhbw_logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.19">

  <meta name="author" content="Prof.&nbsp;Dr.-Ing. Daniel Klünder">
  <title>Mikrocomputertechnik 1</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f355cf95444bdbe7a358cd689c441e6f.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Mikrocomputertechnik 1</h1>
  <p class="subtitle">Einheit 6: Das Steuerwerk</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.-Ing. Daniel Klünder
</div>
</div>
</div>

</section>
<section>
<section id="das-steuerwerk" class="title-slide slide level1 center">
<h1>Das Steuerwerk</h1>
<aside class="notes">
<p>Einheit 5 hat den Datenpfad bereitgestellt. Einheit 6, Mikrocomputertechnik 1, bestimmt, welcher Weg und welche Zustandsänderung zu einem Maschinenbefehl gehören. Das Steuerwerk erzeugt dafür Auswahl- und Freigabesignale. Am Ende sollen Sie die Signale für add, lw, sw und beq im Lehrsubset begründen können. RISC-V schreibt diese interne Schaltung nicht vor.</p>
<p>Kontrollfrage: Steuert das Steuerwerk den Assemblertext oder Bits? Bits und daraus abgeleitete Signale. Die nächste Folie zeigt einen verdrahteten, aber noch nicht passend gesteuerten Prozessor.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-control-unit-als-dirigent-der-hardware" class="slide level2">
<h2>Die Control Unit als Dirigent der Hardware</h2>
<ul>
<li>Herzlich willkommen zur sechsten Vorlesung in Mikrocomputertechnik 1</li>
<li>Letzte Einheit: das physikalische Rohrleitungssystem (Datenpfad)</li>
<li>Multiplexer verlegt, ALU verkabelt, Speichermodule angeschlossen</li>
<li>Das System ist ohne Steuersignale noch leblos</li>
<li>Heute: das Gehirn der CPU — die Control Unit (das Steuerwerk)</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Opcode[Opcode Input] --&gt;|7 Bit| CU[Control Unit]
  CU --&gt;|Steuersignale| Out[MUX / Enable Pins]
  style CU fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Opcode fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Out fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>CPU bedeutet Central Processing Unit, der Prozessor. ALU bedeutet Arithmetic Logic Unit, die arithmetisch-logische Einheit. Ein MUX, Multiplexer, wählt einen Eingang. Der Datenpfad transportiert Werte. Der Registersatz hält Operanden. Der Speicher hält Daten. Das Steuerwerk entscheidet die Auswahlen.</p>
<p>Für add t0, t1, t2 werden zwei Register gelesen, addiert und das Ergebnis nach t0 geschrieben. Der Datenspeicher bleibt unverändert. Kein Bauteil liest den ausgeschriebenen Assemblertext. Die Dirigentenmetapher meint danach Selektor- und Freigabesignale.</p>
<p>Kontrollfrage: Schreibt add in den Datenspeicher? Nein. Die Agenda macht daraus Lernziele.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="agenda-für-den-heutigen-tag" class="slide level2">
<h2>Agenda für den heutigen Tag</h2>
<ol type="1">
<li>Das blinde System — warum Hardware ohne Dirigent kollabiert</li>
<li>Befehlsdecodierung — wie der Chip den Opcode interpretiert</li>
<li>Die Haupt-Steuersignale — Hebel für den gesamten Datenpfad</li>
<li>ALU Control — zweistufige Decodierung (<code>funct3</code> / <code>funct7</code>)</li>
<li>Signal-Trace — die zentrale Wahrheitstabelle ausfüllen</li>
<li>Ripes-Praxis — Vorhersage-Methode („Paper &amp; Pencil“) im Simulator</li>
</ol>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  A[Bedarf] --&gt; B[Opcode decodieren]
  B --&gt; C[Signale generieren]
  C --&gt; D[ALU Steuerung]
  D --&gt; E[Gesamttabelle]
  style E fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style A fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style B fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style C fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style D fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Sechs Abschnitte: Datenpfad reaktivieren, Opcode lesen, Hauptsignale herleiten, ALU-Decodierung trennen, die Meistertabelle füllen und sie mit Ripes vergleichen. Opcode ist der Operationscode. ALU Control ist die nachgelagerte Operationswahl. Ein Signal-Trace verfolgt Werte und Freigaben eines Befehls.</p>
<p>Die Frage ist nicht, ob Hardware ohne Dirigent kollabiert, sondern welche Auswahl und welche Schreibfreigabe korrekt sind. Ripes führt Befehle aus. Sein Single-Cycle-Datenpfad ist später mit diesem Lehrmodell zu vergleichen, nicht damit gleichzusetzen.</p>
<p>Kontrollfrage: Ist Ripes dasselbe Schaltbild wie die Folien? Nein. Zuerst reaktivieren wir den Datenpfad aus Einheit 5.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="rückblick-der-fertige-datenpfad" class="slide level2">
<h2>Rückblick: Der fertige Datenpfad</h2>
<ul>
<li>Lehrmodell nach Patterson/Hennessy, nicht dasselbe Schaltbild wie Ripes</li>
<li>Register, Speicher, ALU und drei Multiplexer</li>
<li>Theoretisch ausführbar: R-Type, Load, Store, Branch</li>
<li>Datenkabel (meist 32 Bit) sind fest verdrahtet</li>
<li>Fehlendes Puzzleteil: die Steuerleitungen „von oben“</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/images/single-cycle-datapath.svg" class=""></p>
<figcaption>Single-Cycle-Datenpfad (vereinfacht)</figcaption>
</figure>
</div>
<aside class="notes">
<p>PC bedeutet Program Counter, die Adresse der aktuellen Instruktion im Modell. Das Register File ist die Registerbank. ImmGen, Immediate Generator, erweitert den unmittelbaren Befehlswert. Die Abbildung ist das Lehrsubset: 32-Bit-Datenpfad, unkomprimierte 32-Bit-Instruktionen, C-Erweiterung aus. Unterstützt sind add, sub, and, or, lw, sw und beq. addi folgt später. bne braucht eine zusätzliche Bedingung.</p>
<p>Die Control Unit gibt Branch aus, nicht fertiges PCSrc. PCSrc, Program Counter Source, entsteht aus Branch und Zero. Der Store-Datenpfad führt den zweiten Registerwert zum Speicher. Der Branch-Zieladdierer ist getrennt von der ALU.</p>
<p>Bei add fließen zwei Registerwerte in die ALU und das Ergebnis ins Zielregister. Bei lw bildet die ALU die Adresse, der Speicher liefert den Schreibwert. Die Grafik ist nicht das Ripes-Schaltbild.</p>
<p>Kontrollfrage: Kommt PCSrc direkt aus der Main Control? Nein. Die festen Leitungen sagen noch nicht, welcher Pfad gilt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-datenpfad-ist-blind" class="slide level2">
<h2>Der Datenpfad ist blind</h2>
<ul>
<li>Kein Bauteil weiß, welchen Befehl Sie in C oder Assembler getippt haben</li>
<li>Die ALU hat keine Augen für <code>add t0, t1, t2</code></li>
<li>Ein Multiplexer schaltet nicht, weil er einen <code>lw</code>-Befehl „merkt“</li>
<li>Jedes Bauteil wartet auf eine physikalische Spannung (1 oder 0)</li>
<li>Fehlt diese Spannung — oder ist sie falsch — kollabiert das System</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb1-1"><a aria-label="1"></a>Ein Multiplexer wählt einen Eingang:</span>
<span id="cb1-2"><a aria-label="2"></a>S = 0 -&gt; Eingang A</span>
<span id="cb1-3"><a aria-label="3"></a>S = 1 -&gt; Eingang B</span>
<span id="cb1-4"><a aria-label="4"></a>Ein falscher Selektor liefert den falschen Operanden.</span>
<span id="cb1-5"><a aria-label="5"></a>Das ist kein Kurzschluss und kein Don't Care.</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Ein MUX wählt abhängig vom Selektor einen Eingang. S gleich 0 wählt A, S gleich 1 wählt B. Ein falscher Selektor liefert den falschen Operanden. Das ist keine Kollision der Daten und kein Einfrieren des Prozessors. Ein physikalisch undefinierter Eingang und ein Don’t Care der späteren Tabelle sind verschieden. Logisch 0 und 1 sind die Signalwerte; konkrete Spannungen hängen vom Bauteil ab und werden hier nicht erfunden.</p>
<p>Kontrollfrage: Kollidieren beide MUX-Eingänge auf der Ausgangsleitung? Nein, einer wird gewählt. Als Nächstes wird die zentrale Steuerung dieser Auswahlen veranschaulicht.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-marionetten-metapher" class="slide level2">
<h2>Die Marionetten-Metapher</h2>
<ul>
<li>Datenpfad als Marionette</li>
<li>Gelenke: Multiplexer und Write-Enable-Pins</li>
<li>Arme und Beine bewegen sich nicht von allein</li>
<li>Puppenspieler: die Control Unit</li>
<li>Kupferfäden: Steuerleitungen — im Takt gezogen, tanzt die Puppe</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph TD
  Puppenspieler[Control Unit] --&gt;|Faden 1| Arm[MUX ALUSrc]
  Puppenspieler --&gt;|Faden 2| Bein[Pin MemWrite]
  Puppenspieler --&gt;|Faden 3| Kopf[MUX PCSrc]
  style Puppenspieler fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Arm fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Bein fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Kopf fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Die Marionette ist nur der Einstieg. Ein Gelenk entspricht einem MUX, der Faden einem Selektor, die Schreibfreigabe einem Enable. Für add gilt ALUSrc gleich 0, also der zweite Registerwert, RegWrite gleich 1 und MemWrite gleich 0. ALUSrc heißt ALU Source, RegWrite Register Write, MemWrite Memory Write.</p>
<p>Kombinatorische Selektoren müssen nicht auf die Taktflanke warten. Zustandselemente übernehmen nach ihrem Taktmodell. Im Kurs ist das die aktive Flanke.</p>
<p>Kontrollfrage: Wechselt ein MUX-Selektor erst bei der Flanke? Nicht zwingend. Die nächste Folie definiert das Steuerwerk als Schaltung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-ist-die-control-unit" class="slide level2">
<h2>Was ist die Control Unit?</h2>
<ul>
<li>Separate, fest verdrahtete Box aus Logikgattern auf dem Chip</li>
<li>In Architekturdiagrammen oft als Wolke oder abgerundete Box</li>
<li>Input: Teile des aktuellen 32-Bit-Befehlsworts</li>
<li>Verarbeitung: reine Kombinatorik (AND/OR-Netzwerke)</li>
<li>Output: 1-Bit- bzw. 2-Bit-Steuersignale an den Datenpfad</li>
</ul>
<aside class="notes">
<p>Die Aussage reine Kombinatorik ohne Flip-Flops gilt für dieses Single-Cycle-Steuerwerk. Single Cycle bedeutet: ein unterstützter Befehl wird in einem Taktzyklus ausgeführt. Andere Steuerwerke können Zustand, mehrere Takte oder ein Mikroprogramm haben. Eine Box im Bild muss keine räumlich getrennte Hardware sein. Input sind Befehlsfelder, Output die benannten Steuersignale. Hardwired Logic heißt fest verdrahtete kombinatorische Logik, nicht eine RISC-V-Pflicht.</p>
<p>Kontrollfrage: Muss jedes Steuerwerk ohne Zustand auskommen? Nein. Als Nächstes kommt die Herkunft der Eingangsbits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="input-woher-kommen-die-befehle" class="slide level2">
<h2>Input: Woher kommen die Befehle?</h2>
<ul>
<li>Der Program Counter adressiert den Befehlsspeicher (Instruction Memory)</li>
<li>Der Speicher liefert 32 Bit (Phase: Instruction Fetch)</li>
<li>Kabelspleiß: ein Teil wandert in den Datenpfad (Register, ImmGen)</li>
<li>Ein anderer Teil wird abgezweigt in die Control Unit</li>
<li>Der Puppenspieler liest physikalisch mit, welcher Code aus dem ROM kommt</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  ROM[(Instruction Memory)] --&gt;|32 Bit| Split{Spleiss}
  Split --&gt;|zu RegFile/ImmGen| Datenpfad[RegFile / ImmGen]
  Split --&gt;|zum Opcode| Control[Control Unit]
  style Control fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style ROM fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Datenpfad fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Der PC adressiert den Befehlsspeicher. Instruction Fetch ist das Holen des 32-Bit-Befehlsworts. Daraus werden Felder an Registerbank, ImmGen und Steuerwerk geführt. Der Befehlsspeicher muss kein ROM sein. ROM, Read-Only Memory, ist nur eine mögliche Speicherart. Ohne C-Erweiterung ist jede Basisinstruktion vier Byte. Das ganze Wort liegt an; verschiedene Blöcke lesen verschiedene Bitpositionen.</p>
<p>Kontrollfrage: Liest das Steuerwerk das gesamte Wort als eine Zahl ohne Felder? Nein, es nutzt festgelegte Positionen. Danach betrachten wir die Ausgänge.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="output-die-blauen-steuerkabel" class="slide level2">
<h2>Output: Die blauen Steuerkabel</h2>
<ul>
<li>Auf der Ausgangsseite treten die Steuerleitungen aus</li>
<li>Für unseren RV32I-Single-Cycle-Prozessor: sieben primäre Steuersignale</li>
<li>Die meisten Signale sind 1 Bit: logischer Pegel 0 oder 1</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Kategorie</th>
<th>Signale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Multiplexer (Weichen)</td>
<td><code>ALUSrc</code>, <code>MemtoReg</code>, Branch (für <code>PCSrc</code>)</td>
</tr>
<tr class="even">
<td>Erlaubnis (Write-Enable)</td>
<td><code>RegWrite</code>, <code>MemWrite</code></td>
</tr>
<tr class="odd">
<td>Leseschutz</td>
<td><code>MemRead</code></td>
</tr>
<tr class="even">
<td>Sondertyp (2 Bit)</td>
<td><code>ALUOp</code> (grobe ALU-Steuerung)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Sieben benannte Hauptsignale ergeben acht Steuerbits, weil ALUOp zwei Bit hat. Das gilt für unseren Lehrsubset-Datenpfad, nicht für jeden RV32I-Prozessor. ALUSrc wählt den zweiten ALU-Operanden. MemtoReg, Memory to Register, wählt den Register-Schreibwert. RegWrite gibt das Registerschreiben frei. MemRead, Memory Read, gibt im Modell den Lesezugriff frei. MemWrite gibt den Schreibzugriff frei. Branch kennzeichnet einen unterstützten bedingten Sprung, ist aber nicht die fertige Sprungentscheidung. ALUOp ist die zweibitige Kategorie, nicht das ALUControl-Wort. PCSrc ist abgeleitet, kein achter Main-Control-Ausgang.</p>
<p>Kontrollfrage: Ist Branch der MUX-Selektor des PC? Nein, PCSrc ist Branch und Zero. Wie entstehen diese Werte zeitlich?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="kombinatorische-logik-das-timing" class="slide level2">
<h2>Kombinatorische Logik (Das Timing)</h2>
<ul>
<li>Wichtige Eigenschaft: Die Control Unit hat keinen eigenen Takt</li>
<li>Reine kombinatorische Schaltung (wie ein großer Addierer)</li>
<li>Kein Zustand, keine Flip-Flops, kein Speicher</li>
<li>Nach der Gatterlaufzeit müssen die Signale vor der Übernahmeflanke stabil sein</li>
<li>Der Datenpfad nutzt sie im Taktzyklus</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb2-1"><a aria-label="1"></a><span class="co">/* Control Unit: rein funktional, kein State */</span></span>
<span id="cb2-2"><a aria-label="2"></a>Steuersignale <span class="op">=</span> generate_control<span class="op">(</span>Instruction_Bits<span class="op">);</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Die Uhrlosigkeit gilt für die kombinatorische Decoderfunktion, nicht für den ganzen Prozessor. Nach einer endlichen Laufzeit müssen die Steuer- und Datenwerte vor der übernehmenden Flanke stabil sein. Kurze Übergangszustände sind möglich. Der längste relevante Pfad begrenzt die zulässige Zykluszeit. Nanosekunden ohne Messung bleiben weg. Ein Pseudocode beschreibt die Funktion und ist kein Programm, das die CPU ausführt.</p>
<p>Kontrollfrage: Stehen die Signale zeitlos fest? Nein, nach der Laufzeit. Eine Wahrheitstabelle spezifiziert die stabile Zuordnung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-wahrheitstabelle-refresher" class="slide level2">
<h2>Die Wahrheitstabelle (Refresher)</h2>
<ul>
<li>Kombinatorik lässt sich vollständig als Wahrheitstabelle beschreiben</li>
<li>Input-Spalten: Bit-Kombinationen der Eingabe</li>
<li>Output-Spalten: resultierende Steuersignale</li>
<li>Die Wahrheitstabelle ist der Bauplan für den Hardware-Entwurf</li>
<li>Heutige Mission: diese Matrix für unseren Prozessor ausfüllen</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Input A</th>
<th>Input B</th>
<th>Output Y (AND)</th>
<th>Output Z (XOR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\ldots\)</span></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>AND ist Und, OR ist Oder, XOR ist exklusives Oder. XOR ist eins bei genau einem gesetzten Eingang, OR auch bei zwei Einsen. Die vier Fälle: 00 ergibt AND 0 und XOR 0; 01 und 10 ergeben AND 0 und XOR 1; 11 ergibt AND 1 und XOR 0. Dieselbe Tabellenidee ordnet später einen Opcode einem Steuerwort zu. Die Tabelle spezifiziert die Funktion. Sie behauptet nicht, dass ebenso viele Zeilen physisch gespeichert werden.</p>
<p>Kontrollfrage: Ist XOR bei zwei Einsen eins? Nein. Eine solche Funktion kann verschieden implementiert werden.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="architektur-design-lut-vs.-gatter" class="slide level2">
<h2>Architektur-Design: LUT vs.&nbsp;Gatter</h2>
<ul>
<li>Methode 1: Hardwired Logic — Karnaugh-Veitch, minimierte AND/OR-Gatter; schnell, aber starr</li>
<li>Methode 2: Microcode (ROM / LUT) — Wahrheitstabelle als Look-up; Opcode als Adresse</li>
<li>RISC-V ist prädestiniert für Hardwired Logic: kleine, effiziente Chips</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Opcode[Opcode] --&gt;|Adresse| ROM[(Microcode ROM)]
  ROM --&gt;|Zeile| Signale[Steuersignale]
  Opcode2[Opcode] --&gt;|Boolesche Formel| Gatter[Gatter-Netzwerk]
  Gatter --&gt; Signale2[Steuersignale]
  style Gatter fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style ROM fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Drei Konzepte: kombinatorische Gatterlogik; eine Look-up Table, kurz LUT, oder eine ROM-Abbildung; ein mikroprogrammiertes Steuerwerk mit Steuerspeicher und Ablauf für interne Schritte. Eine opcode-adressierte Tabelle allein ist noch kein Mikroprogramm. FPGA bedeutet Field-Programmable Gate Array, eine konfigurierbare Logik. Ein ASIC, Application-Specific Integrated Circuit, ist eine feste Fertigung. RISC-V schreibt keine dieser Umsetzungen vor.</p>
<p>Kontrollfrage: Ist jede Tabelle ein Mikroprogramm? Nein. Die nächste Folie ordnet die regelmäßige Codierung als Entwurfshilfe ein.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-risc-v-vorteil" class="slide level2">
<h2>Der RISC-V-Vorteil</h2>
<ul>
<li>x86-Implementierungen nutzen oft Mikrocode oder µOp-Zerlegung</li>
<li>Das ist eine typische Entwurfsentscheidung, kein Beweis, dass Hardwired unmöglich ist</li>
<li>Eine vollständig aufgelistete Wahrheitstabelle ist nicht die synthetisierte Fläche</li>
<li>Konkrete Gatterzahl und Timing brauchen eine Implementierung und Messung</li>
</ul>
<aside class="notes">
<p>Unser Modell trennt Main Control und ALU Control. Die ISA, Instruction Set Architecture, schreibt diese Zerlegung nicht vor. Regelmäßige Felder erleichtern eine strukturierte Decodierung. Sie garantieren keine Chipgröße und keine Taktfrequenz. Eine vollständig aufgelistete Tabelle ist nicht die synthetisierte Fläche. x86 kann intern Micro-Operations, kurz µOps, verwenden; das macht die sichtbare ISA nicht zu diesem Lehrdecoder.</p>
<p>Kontrollfrage: Folgt die Zweiteilung aus der RISC-V-Spezifikation? Nein. Der nächste Abschnitt sucht die relevanten Felder im Befehlswort.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="befehlsdecodierung-und-opcode" class="title-slide slide level1 center">
<h1>Befehlsdecodierung und Opcode</h1>
<aside class="notes">
<p>Eingänge und Ausgänge sind bekannt. Jetzt wird die Eingangsinformation gezielt reduziert. Der Opcode ist der Operationscode zur Familienerkennung. Die Leitfrage lautet: Welche Bits steuern die Pfadauswahl, und welche führen Operanden oder Registeradressen? Nicht jedes Bit des Befehlsworts ist ein Steuersignal.</p>
<p>Kontrollfrage: Decodiert der Opcode allein add gegen sub? Nein. Die nächste Folie motiviert eine strukturierte statt erschöpfende Analyse.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wir-müssen-den-befehl-lesen-aber-wie" class="slide level2">
<h2>Wir müssen den Befehl lesen — aber wie?</h2>
<ul>
<li>Die Control Unit muss den Befehl interpretieren</li>
<li>Müssen wirklich alle 32 Bits gleichzeitig analysiert werden?</li>
<li>Antwort liefert die Anatomie der RISC-V-Formate</li>
<li>Der 7-Bit-<code>opcode</code> als Identifikationsschild</li>
<li>Das Konzept Don’t Care (<span class="math inline">\(X\)</span>) und warum es Hardware spart</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph TD
  Inst[32-Bit Befehl] --&gt;|Filterung| Opcode[Nur 7 Bits Opcode]
  Opcode --&gt; Control[Main Control Unit]
  style Control fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Inst fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Opcode fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>2 hoch 32 ist 4 294 967 296 mögliche Bitmuster. Das ist die Größe einer naiv vollständig aufgelisteten Tabelle, nicht die Gatterzahl. Eine strukturierte Funktion wertet Felder getrennt und gemeinsame Bedingungen zusammen aus. Ein X in einer späteren Tabelle erlaubt nicht, gültigkeitsrelevante Bits zu ignorieren.</p>
<p>Kontrollfrage: Muss ein Decoder 4 Milliarden Zeilen speichern? Nein. Die Formate zeigen, welche Felder an welcher Position stehen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-anatomie-des-befehls-refresher" class="slide level2">
<h2>Die Anatomie des Befehls (Refresher)</h2>
<ul>
<li>Instruction Formats R, I, S, B aus Einheit 2</li>
<li>Felder wie <code>rs1</code> (Bits 19:15) oder <code>rd</code> (Bits 11:7) sind Registeradressen</li>
<li>Die Control Unit interessiert sich nicht für diese Hausnummern</li>
<li>Ob <code>t0</code> oder <code>s11</code> addiert wird: MUX-Stellungen bleiben gleich</li>
<li>Diese Bits können wir für das Steuerwerk ignorieren</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb3-1"><a aria-label="1"></a>31          24    19    14      11      7       0</span>
<span id="cb3-2"><a aria-label="2"></a>+-------+-----+-----+-------+-----+-------------+</span>
<span id="cb3-3"><a aria-label="3"></a>| funct7| rs2 | rs1 | funct3|  rd |   opcode    |</span>
<span id="cb3-4"><a aria-label="4"></a>+-------+-----+-----+-------+-----+-------------+</span>
<span id="cb3-5"><a aria-label="5"></a>  (Detail)  (ignoriert)  (Detail)   WICHTIG!</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>R-Type: funct7 in 31 bis 25, rs2 in 24 bis 20, rs1 in 19 bis 15, funct3 in 14 bis 12, rd in 11 bis 7, opcode in 6 bis 0. rs bedeutet source register, rd destination register, funct Funktionsfeld. Die 15 Registerbits gelten nur für diesen R-Type. I-Type ersetzt funct7 und rs2 durch ein 12-Bit-Immediate. S- und B-Type haben kein rd. Ihre Bits 11 bis 7 tragen Immediate-Anteile. Der Immediate ist gesplittet und nicht ein zusammenhängendes Feld.</p>
<p>Kontrollfrage: Enthält sw ein rd-Feld? Nein. In allen betrachteten Formaten liegt der Opcode an derselben Position.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-7-bit-identifikationsschild" class="slide level2">
<h2>Das 7-Bit-Identifikationsschild</h2>
<ul>
<li>In jedem Format an derselben Stelle: der <code>opcode</code></li>
<li>Bits <span class="math inline">\([6:0]\)</span> — exakt 7 Bit breit</li>
<li>Diese 7 Drähte sind der Input der Main Control Unit</li>
<li>Der Opcode sagt die Befehlsfamilie, nicht <code>add</code> vs.&nbsp;<code>sub</code></li>
<li>Detailentscheidungen folgen später über <code>funct3</code> / <code>funct7</code></li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Kabel[32 Bit vom IM] --&gt; Spleiss{Spleiss}
  Spleiss --&gt;|Bits 31:7| Rest[Datenpfad / ALU-Ctrl]
  Spleiss --&gt;|Bits 6:0| Control((Main Control))
  style Control fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Kabel fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Rest fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Die Bits 6 bis 0 sind sieben Positionen einschließlich beider Grenzen. 2 hoch 7 ist 128 mögliche Opcode-Werte. Nicht alle werden in diesem Subset genutzt. add und sub teilen 0110011. Die konkrete Operation steht in funct3 und funct7. Nur nach dem Opcode zu entscheiden ist eine Modellwahl für die gezeigten Pfadauswahlen. Weitere Details brauchen zusätzliche Decoder.</p>
<p>Kontrollfrage: Reicht der Opcode, um add von sub zu unterscheiden? Nein. Zuerst folgt die Familie der Register-Rechenbefehle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="opcode-r-type-rechnen" class="slide level2">
<h2>Opcode: R-Type (Rechnen)</h2>
<ul>
<li>Familie: zwei Register lesen, rechnen, in ein Register schreiben (<code>add</code>, <code>sub</code>, <code>and</code>, <code>or</code>, <code>sll</code>, …)</li>
<li>Opcode (binär): <code>0110011</code></li>
<li>Keine Konstanten nötig; RAM unbeteiligt; <code>RegWrite</code> zwingend</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bit 6</th>
<th>Bit 5</th>
<th>Bit 4</th>
<th>Bit 3</th>
<th>Bit 2</th>
<th>Bit 1</th>
<th>Bit 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>0110011 ist hexadezimal 0x33. In dieser Zeile unterstützen wir add, sub, and und or mit legalen Encodings. sll ist ein echter weiterer R-Type-Befehl, aber nicht durch die aktuelle ALU-Control-Tabelle abgedeckt. t0, t1 und t2 sind Aliase temporärer Register. Lehrwerte: t1 gleich 7, t2 gleich 3, add t0, t1, t2 schreibt 10. Die Quellen bleiben unverändert.</p>
<p>Kontrollfrage: Deckt die Zeile jeden R-Type-Befehl ab? Nein. Load hat einen anderen Datenweg.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="opcode-load-familie-im-i-format" class="slide level2">
<h2>Opcode: Load-Familie im I-Format</h2>
<ul>
<li>Familie: Daten aus dem Arbeitsspeicher in die CPU (<code>lw</code>, <code>lb</code>, <code>lh</code>, …)</li>
<li>Opcode (binär): <code>0000011</code></li>
<li>Immediate für Adressberechnung; RAM lesen; Write-Back aus dem RAM</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bit 6</th>
<th>Bit 5</th>
<th>Bit 4</th>
<th>Bit 3</th>
<th>Bit 2</th>
<th>Bit 1</th>
<th>Bit 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>0000011, hexadezimal 0x03, kennzeichnet Loads, nicht alle I-Type-Befehle. addi hat 0010011, also 0x13. lw bedeutet Load Word und lädt 32 Bit. lb und lh brauchen Breiten- und Erweiterungssteuerung, die nicht in der Grundmatrix steht. Die ALU bildet Basis plus vorzeichenerweiterten Offset. Die Adresse ist nicht der geladene Wert.</p>
<p>Kontrollfrage: Hat addi denselben Opcode wie lw? Nein. Store verwendet eine ähnliche Adresse und schreibt in die andere Richtung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="opcode-s-type-store" class="slide level2">
<h2>Opcode: S-Type (Store)</h2>
<ul>
<li>Familie: CPU-Daten im RAM ablegen (<code>sw</code>, <code>sb</code>, <code>sh</code>)</li>
<li>Opcode (binär): <code>0100011</code></li>
<li>Immediate für Adresse; <code>MemWrite</code> aktiv; kein <code>rd</code> → <code>RegWrite = 0</code></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bit 6</th>
<th>Bit 5</th>
<th>Bit 4</th>
<th>Bit 3</th>
<th>Bit 2</th>
<th>Bit 1</th>
<th>Bit 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>sw bedeutet Store Word. Der Opcode ist 0100011, hexadezimal 0x23. Die Basis kommt aus rs1, die Store-Daten aus rs2, der Offset ist ein gesplitteter S-Immediate. Die ALU wählt den Immediate als zweiten Operanden. Der zweite Registerwert bleibt trotzdem am Speicher-Schreibdateneingang verfügbar. sb und sh brauchen zusätzliche Schreibmasken.</p>
<p>Kontrollfrage: Verschwindet rs2, weil ALUSrc den Immediate wählt? Nein, es liefert die Schreibdaten. Branch verändert vor allem die nächste Befehlsadresse.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="opcode-b-type-branch" class="slide level2">
<h2>Opcode: B-Type (Branch)</h2>
<ul>
<li>Familie: bedingte Sprünge (<code>beq</code>, <code>bne</code>, <code>blt</code>, …)</li>
<li>Opcode (binär): <code>1100011</code></li>
<li>Registervergleich; nichts schreiben; Sprungentscheidung mit ALU-Flag</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bit 6</th>
<th>Bit 5</th>
<th>Bit 4</th>
<th>Bit 3</th>
<th>Bit 2</th>
<th>Bit 1</th>
<th>Bit 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>beq bedeutet Branch if Equal, bne Branch if Not Equal, blt Branch if Less Than. Der Opcode 1100011, hexadezimal 0x63, erkennt die Familie. funct3 unterscheidet die Bedingung. Das bisherige Zero-Netz gilt für beq. bne braucht die negierte Gleichheit. blt und bltu unterscheiden signed und unsigned. Zero ist kein architektonisches Flag. RegWrite und MemWrite bleiben im Modell null. Der PC wird trotzdem aktualisiert.</p>
<p>Kontrollfrage: Deckt Branch und Zero auch bne ab? Nein. Die Familienerkennung wird in der Main-Control-Box zusammengefasst.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-main-control-block" class="slide level2">
<h2>Der Main-Control-Block</h2>
<ul>
<li>Blackbox konkret: exakt 7 Bit Eingang</li>
<li>Ausgang: Bündel an Kontrollsignalen</li>
<li>Signale fließen zu Multiplexern und Speicher-Pins</li>
<li>Nächste Aufgabe: Wahrheitstabelle Zeile für Zeile lösen</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Opcode[7 Bits Opcode] --&gt; Box((Main Control Unit))
  Box --&gt;|1 Bit| ALUSrc
  Box --&gt;|1 Bit| MemtoReg
  Box --&gt;|1 Bit| RegWrite
  Box --&gt;|2 Bit| ALUOp
  style Box fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Opcode fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Sieben Opcode-Bits gehen hinein. Hinaus gehen die sieben benannten Signale mit acht Bits. Die Box decodiert nicht sämtliche RV32I-Befehle. ALU-Detail, Speicherbreite und Branch-Bedingung brauchen zusätzliche Information. Pfeile zeigen die Richtung von Opcode zu den Signalen.</p>
<p>Kontrollfrage: Reichen diese Ausgänge für jal? Nein, jal fehlt im Lehrsubset. Vor dem Füllen der Tabelle klären wir, wann ein Ausgang unerheblich ist.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-konzept-dont-care-x" class="slide level2">
<h2>Das Konzept Don’t Care (<span class="math inline">\(X\)</span>)</h2>
<ul>
<li>Ingenieurswerkzeug: Don’t Care (<span class="math inline">\(X\)</span>)</li>
<li>Beispiel: <code>MemtoReg</code> bei <code>sw</code> — Store schreibt nie ins Register File (<code>RegWrite = 0</code>)</li>
<li>Welches Kabel der MUX durchlässt, ist irrelevant</li>
<li>In die Wahrheitstabelle: <span class="math inline">\(X\)</span> statt 0 oder 1</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb4-1"><a aria-label="1"></a>MemtoReg bei sw:</span>
<span id="cb4-2"><a aria-label="2"></a>Muss es 0 sein (ALU)?  -&gt; Nein</span>
<span id="cb4-3"><a aria-label="3"></a>Muss es 1 sein (RAM)?  -&gt; Nein</span>
<span id="cb4-4"><a aria-label="4"></a>Also: X (Don't Care)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Bei sw ist RegWrite gleich 0. Der Register-Schreibport übernimmt keinen Wert. Deshalb darf MemtoReg in der Tabelle 0 oder 1 sein. Beide Stellungen lassen denselben Registerzustand. X bedeutet diese Entwurfsfreiheit, nicht einen schwebenden Pegel und nicht einen abgeschalteten Draht. In der konkreten Schaltung hat der Draht trotzdem 0 oder 1. HDL, Hardware Description Language, benutzt X manchmal für einen unbekannten Simulationswert und Z für hochohmig. Das sind andere Bedeutungen.</p>
<p>Kontrollfrage: Ist der Draht bei X elektrisch offen? Nein. Diese Freiheit kann die Minimierung erleichtern.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-x-hardware-spart" class="slide level2">
<h2>Warum <span class="math inline">\(X\)</span> Hardware spart</h2>
<ul>
<li><span class="math inline">\(X\)</span> gibt dem Synthese-Tool (Quartus, Vivado) Freiheit</li>
<li>Im Karnaugh-Veitch-Diagramm: <span class="math inline">\(X\)</span> wahlweise als 1 oder 0 für große Blöcke</li>
<li>Große Blöcke → kurze Boolesche Formeln</li>
<li>Kurze Formeln → weniger Gatter, weniger Strom, höhere Taktraten</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph TD
  X[Don't Care in Tabelle] --&gt; KV[KV-Diagramm]
  KV --&gt; Formel[kürzere Formel]
  Formel --&gt; Silizium[Kleinerer Chip]
  style Silizium fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style X fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style KV fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Formel fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>X kann eine Boolesche Minimierung erleichtern. Es garantiert nicht weniger Fläche, Strom oder eine höhere Taktfrequenz. Ein Karnaugh-Veitch-Diagramm ordnet Eingaben so, dass benachbarte Einsen zusammengefasst werden. Kleines Beispiel: f(00) gleich 0, f(01) gleich 1, f(10) gleich 0, f(11) gleich X. Wählt man X als 1, gilt f gleich B. Das ist Algebra, keine Messung dieses Prozessors.</p>
<p>Kontrollfrage: Spart jedes X einen Transistor? Nicht nachweisbar ohne Synthese. Die leere Haupttabelle kann nun gefüllt werden.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-skelett-tabelle" class="slide level2">
<h2>Die Skelett-Tabelle</h2>
<ul>
<li>Leere Wahrheitstabelle als Arbeitsblatt</li>
<li>Vier Zeilen für die wichtigsten Opcodes</li>
<li>Spalten für die entscheidenden Steuersignale</li>
<li>Nächste Folien: Matrix durch logisches Denken füllen</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Instruktion (Opcode)</th>
<th>ALUSrc</th>
<th>MemtoReg</th>
<th>RegWrite</th>
<th>MemRead</th>
<th>MemWrite</th>
<th>Branch</th>
<th>ALUOp1</th>
<th>ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R-Type (<code>0110011</code>)</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
</tr>
<tr class="even">
<td><code>lw</code> (<code>0000011</code>)</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
</tr>
<tr class="odd">
<td><code>sw</code> (<code>0100011</code>)</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
</tr>
<tr class="even">
<td><code>beq</code> (<code>1100011</code>)</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
<td>?</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Spalten sind ALUSrc, MemtoReg, RegWrite, MemRead, MemWrite, Branch und das zweibitige ALUOp. Fragezeichen bedeuten noch offen. X bedeutet begründet unerheblich. Die R-Type-Zeile meint die ausgewählten Operationen add, sub, and und or, nicht alle Encodings mit Opcode 0110011. Jede Zeile wird über Quellen, Berechnung, Ziel und Zustandsänderung hergeleitet.</p>
<p>Kontrollfrage: Ist ein Fragezeichen dasselbe wie X? Nein. Eine Gruppierung unterstützt die Herleitung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-spalten-gruppieren" class="slide level2">
<h2>Die Spalten gruppieren</h2>
<ul>
<li>Output-Pins mental nach CPU-Phase ordnen</li>
<li>Execute (ALU): <code>ALUSrc</code>; <code>ALUOp1</code>/<code>ALUOp0</code> für die grobe ALU-Aufgabe</li>
<li>Memory (RAM): <code>MemRead</code>, <code>MemWrite</code>; Branch für die Sprung-Erlaubnis</li>
<li>Write-Back: <code>MemtoReg</code> und <code>RegWrite</code></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb5-1"><a aria-label="1"></a>Signalfluss in der CPU: von links nach rechts.</span>
<span id="cb5-2"><a aria-label="2"></a>Tabelle gedanklich in derselben Richtung ausfüllen.</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>EX bedeutet Execute, MEM Memory Access, WB Write Back. Das sind Funktionsabschnitte dieses Single-Cycle-Datenpfads, keine eigenen Taktzyklen und keine Pipeline. Branch gehört nicht zum Datenspeicher, sondern zur PC-Auswahl. Farben allein genügen nicht; die Gruppen sind beschriftet.</p>
<p>Kontrollfrage: Sind EX, MEM und WB drei Takte? Hier nein. Schreib- und PC-Signale müssen präzise festgelegt werden.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-eiserne-gesetz-der-präzision" class="slide level2">
<h2>Das eiserne Gesetz der Präzision</h2>
<ul>
<li>Ein Fehler in der Matrix kann das System crashen lassen</li>
<li>Beispiel: <code>RegWrite</code> bei <code>sw</code> vergessen und auf 1 gesetzt</li>
<li>Die Schreibadresse ist das Bitfeld, das im R-Format <code>rd</code> wäre</li>
<li>Bei <code>sw</code> sind das Teile des Immediate; das beschriebene Register folgt aus diesen Bits</li>
<li>Der Schreibwert ist der am Write-Data-Eingang anliegende Wert, nicht unbestimmter Abfall</li>
</ul>
<aside class="notes">
<p>sw t1, 12(s1) trägt im S-Immediate an den Bits 11 bis 7 den Wert 01100. Ein fälschlich aktiver Register-Schreibport würde damit x12 adressieren. Das ist kein zufälliges Register. Steht MemtoReg in diesem Fehlerbild auf 0, wäre der ALU-Adresswert der Schreibwert, nicht undefinierter Inhalt. Eine ASIC-Änderung ist nicht die zwingende Folge; ein FPGA oder ein Modell kann anders geändert werden.</p>
<p>Kontrollfrage: Sieht der Schreibport bei sw ein echtes rd? Nein. Anschließend prüfen wir jedes Signal einzeln.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="die-haupt-steuersignale" class="title-slide slide level1 center">
<h1>Die Haupt-Steuersignale</h1>
<aside class="notes">
<p>Der Abschnitt wechselt von Opcode-Familien zu Bauteilwirkungen. Für jeden Pin lautet die Frage: Welche Auswahl oder Zustandsänderung steuert er, und wann ist sein Wert beobachtbar? Die sieben Namen sind die Orientierung. Ihre Begründung folgt einzeln.</p>
<p>Kontrollfrage: Ist ein anliegender Datenwert schon gespeichert? Nein. Die nächste Folie gruppiert die Signale.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-signale-im-überblick" class="slide level2">
<h2>Die Signale im Überblick</h2>
<ul>
<li>Jedes der sieben Steuersignale systematisch durchgehen</li>
<li>Welche Signale sind Weichen (MUX)?</li>
<li>Welche Signale sind Schreib-/Leserechte (Enable-Pins)?</li>
<li>Warum sind Don’t Cares (<span class="math inline">\(X\)</span>) bei MUXen oft sinnvoll?</li>
<li>Die fatale Kollision von <code>MemRead</code> und <code>MemWrite</code></li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph TD
  A[Steuersignale] --&gt; B[Multiplexer]
  A --&gt; C[Enable Pins]
  B --&gt;|Pfadwahl| D[z.B. ALUSrc]
  C --&gt;|Erlaubt Speichern| E[z.B. RegWrite]
  style A fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style B fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style C fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style D fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style E fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Ein MUX wählt eine Datenquelle. Ein Enable gibt einen Zugriff frei. Branch ist eine Bedingungsfreigabe, nicht der Speicherzugriff. MemRead und MemWrite gleichzeitig sind in unserem Modell nicht die vorgesehene Kombination. Das ist eine Modellregel, keine universelle elektrische Kurzschlussgefahr.</p>
<p>Kontrollfrage: Dürfen MemRead und MemWrite im Lehrsubset beide eins sein? Nein. Als Nächstes unterscheiden wir anliegende Daten und ihre Speicherung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zwei-arten-von-signalen" class="slide level2">
<h2>Zwei Arten von Signalen</h2>
<ul>
<li>Im Datenpfad gibt es zwei Kategorien von Steuerleitungen</li>
<li>Kategorie 1: Weichen (Multiplexer) — lenken Datenströme (z. B. <code>ALUSrc</code>)</li>
<li>Eine Weiche leitet immer weiter — auch bei Müll; sie steht auf 0 oder 1</li>
<li>Kategorie 2: Erlaubnis-Pins (Write-Enable) — verändern Speicherzustand (z. B. <code>RegWrite</code>)</li>
<li>Enable-Pins restriktiv auf 0 halten; nur bei Bedarf 1 — sonst Datenkorruption</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Control[Control Unit] --&gt;|Kategorie 1| MUX{Multiplexer}
  Control --&gt;|Kategorie 2| Enable[Enable Pins]
  style Control fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style MUX fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Enable fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Der MUX-Ausgang führt den ausgewählten Datenwert. Er ist kein Schreibport. Ein Register übernimmt den Wert erst bei erlaubter Freigabe und der Modellflanke. Ob ein Wert unerheblich ist, muss für jeden beobachtbaren Verbraucher geprüft werden, nicht nur für das Write-Back. Die Skizze trennt Datenpfad und Enable.</p>
<p>Kontrollfrage: Verändert ein MUX-Ausgang allein den Registerzustand? Nein. ALUSrc ist das erste Auswahlbeispiel.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="alusrc-multiplexer-1" class="slide level2">
<h2>ALUSrc (Multiplexer 1)</h2>
<ul>
<li>1-Bit-Signal steuert den MUX vor dem zweiten ALU-Eingang</li>
<li>0: ALU rechnet mit Register <code>RD2</code> aus dem Register File</li>
<li>1: ALU rechnet mit der 32-Bit-Konstante aus dem ImmGen</li>
<li>Reine Registeroperationen (<code>add</code>, <code>sub</code>, <code>and</code>) → <code>ALUSrc = 0</code></li>
<li>Adress-Offsets (<code>lw</code>, <code>sw</code>) → <code>ALUSrc = 1</code></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb6-1"><a aria-label="1"></a>ALUSrc:</span>
<span id="cb6-2"><a aria-label="2"></a>R-Type  -&gt; 0   (rs2)</span>
<span id="cb6-3"><a aria-label="3"></a>Load    -&gt; 1   (Immediate-Offset)</span>
<span id="cb6-4"><a aria-label="4"></a>Store   -&gt; 1   (Immediate-Offset)</span>
<span id="cb6-5"><a aria-label="5"></a>Branch  -&gt; 0   (Register vergleichen)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>ALUSrc gleich 0 wählt RD2, den zweiten gelesenen Registerdatenwert. ALUSrc gleich 1 wählt den auf 32 Bit erweiterten Immediate. add nutzt Register plus Register. lw und sw nutzen Basis plus Offset. beq nutzt im Lehrmodell die Register für den Vergleich. addi nutzt ebenfalls die Immediate-Auswahl. In Ripes ist die Branch-Struktur anders; diese 0 gilt hier für das Lehrmodell.</p>
<p>Kontrollfrage: Welche ALUSrc-Stellung hat lw? 1. Danach wird die Quelle des Register-Schreibwerts gewählt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="memtoreg-multiplexer-2" class="slide level2">
<h2>MemtoReg (Multiplexer 2)</h2>
<ul>
<li>1-Bit-Signal steuert den MUX vor dem Write-Back</li>
<li>0: ALU-Ergebnis fließt ins Zielregister</li>
<li>1: RAM-Daten fließen ins Zielregister</li>
<li>RAM-Daten nur beim Load (<code>lw</code>)</li>
<li>Bei R-Type muss <code>MemtoReg = 0</code> sein — sonst RAM-Schrott in der Variablen</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb7-1"><a aria-label="1"></a>MemtoReg:</span>
<span id="cb7-2"><a aria-label="2"></a>R-Type  -&gt; 0   (ALU-Ergebnis)</span>
<span id="cb7-3"><a aria-label="3"></a>Load    -&gt; 1   (RAM-Daten)</span>
<span id="cb7-4"><a aria-label="4"></a>Branch  -&gt; X   (kein Speichern)</span>
<span id="cb7-5"><a aria-label="5"></a>Store   -&gt; X   (kein Speichern)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>MemtoReg gleich 0 wählt das ALU-Ergebnis, gleich 1 den gelesenen Speicherwert. Lehrwerte: die ALU berechnet die Adresse 0x2004, der Speicher enthält dort 37. lw schreibt 37, nicht die Adresse. Ein falscher Datenwert ist ein bestimmter anderer Wert, kein Schrott. Ripes kann mehr als zwei Write-Back-Quellen haben, darunter PC plus 4.</p>
<p>Kontrollfrage: Was schreibt lw in diesem Beispiel? 37. Ohne Registerschreiben kann die Auswahl unerheblich sein.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="memtoreg-als-dont-care-x" class="slide level2">
<h2>MemtoReg als Don’t Care (<span class="math inline">\(X\)</span>)</h2>
<ul>
<li>Bei <code>sw</code> oder <code>beq</code>: nichts wird ins Register File geschrieben</li>
<li><code>RegWrite = 0</code> — Werkbank verschlossen</li>
<li>MUX-Stellung vor dem Register File ist irrelevant</li>
<li>Signale prallen am geschlossenen Register File ab</li>
<li>In die Wahrheitstabelle: stolzes <span class="math inline">\(X\)</span></li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph RL
  MUX{MemtoReg = X} --&gt;|prallt ab| Reg[(Register File)]
  RegWrite[RegWrite = 0] -.-&gt;|geschlossen| Reg
  style RegWrite fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style MUX fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Reg fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>RegWrite gleich 0 deaktiviert den betrachteten Schreibport. Die Leseports können rs1 und rs2 weiter liefern. Die Registerbank ist nicht insgesamt geschlossen. Bei sw bleiben Adresse, Store-Daten und MemWrite relevant. MemtoReg gleich 0 und gleich 1 erzeugen denselben Registerzustand, weil nichts übernommen wird.</p>
<p>Kontrollfrage: Dürfen die Leseports bei sw weiter Daten liefern? Ja. Die nächste Folie erklärt die Schreibfreigabe genauer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="regwrite-erlaubnis-pin" class="slide level2">
<h2>RegWrite (Erlaubnis-Pin)</h2>
<ul>
<li>Hochkritischer Write-Enable am Register File</li>
<li>1: Bei der nächsten positiven Taktflanke wird <code>rd</code> überschrieben</li>
<li>0: Register File schreibgeschützt</li>
<li>Fehler hier sind für die Software katastrophal</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb8-1"><a aria-label="1"></a>RegWrite:</span>
<span id="cb8-2"><a aria-label="2"></a>R-Type  -&gt; 1   (Ergebnis speichern)</span>
<span id="cb8-3"><a aria-label="3"></a>Load    -&gt; 1   (geladenes Wort speichern)</span>
<span id="cb8-4"><a aria-label="4"></a>Store   -&gt; 0</span>
<span id="cb8-5"><a aria-label="5"></a>Branch  -&gt; 0</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>RegWrite ist die Schreibfreigabe. Write Enable ist dasselbe Signal in manchen Bildern. rd ist die Zieladresse. Die positive Flanke ist die Annahme dieses Modells, keine ISA-Pflicht. x0 bleibt immer null, auch wenn rd gleich x0 ist. PC und Datenspeicher sind andere Zustandselemente. RegWrite gleich 0 blockiert sie nicht. Vor der Flanke kann das ALU-Ergebnis schon anliegen. Erst die Freigabe übernimmt es nach t0.</p>
<p>Kontrollfrage: Setzt RegWrite gleich 0 auch den PC still? Nein. Store und Branch brauchen dieses Write-Back nicht.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wer-darf-nicht-schreiben" class="slide level2">
<h2>Wer darf nicht schreiben?</h2>
<ul>
<li>Zwei Familien dürfen <code>RegWrite</code> nie aktivieren</li>
<li>Store (<code>sw</code>): Ziel ist der RAM; CPU-Variablen bleiben unangetastet</li>
<li>Branch (<code>beq</code>): Ziel ist der PC; keine Datenberechnung/-ladung</li>
<li>Control Unit zwingt <code>RegWrite</code> eisern auf 0</li>
<li>Ein fälschlich aktives <code>RegWrite</code> würde die Immediate-Bits als Registeradresse sehen</li>
</ul>
<aside class="notes">
<p>S- und B-Format haben kein rd. Ein naiver Adressport sieht Immediate-Bits. Die Wirkung einer falschen Freigabe ist aus Adresse und Schreibwert bestimmbar, nicht zufällig. Bei den behandelten Stores und Branches bleibt der allgemeine Registersatz unverändert. Store ändert den Datenspeicher, Branch den PC.</p>
<p>Kontrollfrage: Welches Register würde 01100 fälschlich wählen? x12. Nun folgen die Speicherzugriffe.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="memread-erlaubnis-pin" class="slide level2">
<h2>MemRead (Erlaubnis-Pin)</h2>
<ul>
<li>Erlaubnis-Pin für das Lesen aus dem Datenspeicher (RAM)</li>
<li>1: RAM legt Bits an der ALU-Adresse auf das Lesekabel</li>
<li>0: im Lehrmodell kein vorgesehener Lesezugriff, nicht automatisch hochohmig</li>
<li>Im Single-Cycle nur bei <code>lw</code> auf 1</li>
<li>Sonst Strom sparen: RAM nicht unnötig auslesen</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb9-1"><a aria-label="1"></a>MemRead:</span>
<span id="cb9-2"><a aria-label="2"></a>Load         -&gt; 1</span>
<span id="cb9-3"><a aria-label="3"></a>Alle anderen -&gt; 0</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>MemRead ist die explizite Lesezugriffssteuerung des Lehrmodells. MemRead gleich 0 bedeutet hier keinen vorgesehenen Lesezugriff. Ob der Ausgang dann einen Pegel oder einen hochohmigen Zustand hat, entscheidet die konkrete Speicherimplementierung. Ripes steuert Zugriffsart und Breite oft über einen Operationsselektor, nicht zwingend über einen gleichnamigen Pin. Eine Stromersparnis ist implementationsabhängig und hier nicht gemessen.</p>
<p>Kontrollfrage: Bedeutet MemRead gleich 0 immer den Zustand Z? Nein. Schreiben ist ein eigener Zugriff.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="memwrite-erlaubnis-pin" class="slide level2">
<h2>MemWrite (Erlaubnis-Pin)</h2>
<ul>
<li>Noch kritischerer Write-Enable am RAM</li>
<li>1: Bei Taktflanke wird Write-Data in die RAM-Zelle geschrieben</li>
<li>0: Schreibschutz aktiv</li>
<li>In der Basistabelle genau einmal 1: bei <code>sw</code></li>
<li>Ein falsches <code>MemWrite</code> kann den konkret adressierten Speicherwert ändern</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb10-1"><a aria-label="1"></a>MemWrite:</span>
<span id="cb10-2"><a aria-label="2"></a>Store        -&gt; 1</span>
<span id="cb10-3"><a aria-label="3"></a>Alle anderen -&gt; 0</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>MemWrite braucht drei getrennte Angaben: Adresse, Schreibdaten und Freigabe. Bei sw kommt die Adresse aus der ALU und der Schreibwert aus rs2. Die Übernahme folgt dem Speichertaktmodell. Ein falsches MemWrite kann den adressierten Wert ändern. Es gibt hier nicht automatisch ein Betriebssystem, das dadurch abstürzt.</p>
<p>Kontrollfrage: Liegt der Store-Wert am ALU-Ergebnis? Nein, an rs2. Die nächste Folie legt die zulässigen Kombinationen fest.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-gefahr-memread-und-memwrite" class="slide level2">
<h2>Die Gefahr: MemRead und MemWrite</h2>
<ul>
<li>Im Lehrmodell sind <code>MemRead</code> und <code>MemWrite</code> gegenseitig ausgeschlossen</li>
<li><code>MemRead = 0</code> bedeutet hier „nicht lesen“, nicht zwingend hochohmig</li>
<li>Ein elektrischer Kurzschluss gilt nur für ein konkret gezeigtes Busmodell</li>
<li>Speichermodule können ein definiertes Read-during-write haben; das nutzen wir nicht</li>
</ul>
<aside class="notes">
<p>Die vier Kombinationen, zuerst MemRead dann MemWrite: 00 kein vorgesehener Zugriff, 10 lesen, 01 schreiben, 11 im Kursmodell nicht verwendet. Read-during-write realer Speicher ist eine eigene Spezifikation, kein automatischer Kurzschluss. Für lw gilt 10, für sw 01, für add und beq 00.</p>
<p>Kontrollfrage: Welche Kombination hat sw? MemRead 0 und MemWrite 1. Die letzte Gruppe betrifft den Kontrollfluss.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="branch-entscheidungs-signal" class="slide level2">
<h2>Branch (Entscheidungs-Signal)</h2>
<ul>
<li>Weder direkter MUX noch Enable-Pin</li>
<li>Hilfssignal in das AND-Gatter vor dem PC</li>
<li>1: Control Unit bestätigt — aktueller Befehl ist bedingter Sprung</li>
<li>Liefert dem AND die halbe Erlaubnis für <code>PCSrc</code></li>
<li>Bei <code>add</code>, <code>lw</code>, <code>sw</code>: Branch = 0 — Sprung unmöglich</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb11-1"><a aria-label="1"></a>Branch:</span>
<span id="cb11-2"><a aria-label="2"></a>beq / Branch-Familie -&gt; 1</span>
<span id="cb11-3"><a aria-label="3"></a>Alle anderen         -&gt; 0</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Branch gleich 1 kennzeichnet einen unterstützten bedingten Sprung. Es bedeutet nicht, dass der Sprung genommen wird. PCSrc ist die Auswahl des nächsten PC. jal und jalr fehlen im Lehrsubset. Dieselbe Branch-Freigabe kann mit verschiedenen Vergleichsergebnissen verschiedenes PCSrc erzeugen.</p>
<p>Kontrollfrage: Ist Branch gleich 1 schon das genommene Sprungziel? Nein. Die nächste Folie setzt die Gleichung zusammen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-pcsrc-logik-rückblick" class="slide level2">
<h2>Die PCSrc-Logik (Rückblick)</h2>
<ul>
<li>Control Unit kann die finale Sprungentscheidung nicht allein fällen</li>
<li>Registervergleich fehlt ihr — ALU-Zero als Assistent</li>
<li>Für <code>beq</code>: <span class="math inline">\(\mathrm{PCSrc} = \mathrm{Branch} \land \mathrm{Zero}\)</span></li>
<li>Beide Signale müssen 1 sein, damit der PC umgeschaltet wird</li>
<li>Andere Branches (z. B. <code>bne</code>): andere Flag-Logik (oft <span class="math inline">\(\mathrm{Branch} \land \overline{\mathrm{Zero}}\)</span>)</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Control[Branch] --&gt; AND((AND))
  ALU[Zero-Flag] --&gt; AND
  AND --&gt;|steuert PC| MUX{PCSrc MUX}
  style AND fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Control fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style ALU fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style MUX fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Für beq gilt PCSrc gleich Branch und Zero. Zero ist eins genau bei ALU-Ergebnis null. Die vier Fälle: Branch 0 und Zero 0 oder 1 lassen den Sprung ungewählt. Branch 1 und Zero 0 ergibt PCSrc 0, also PC plus 4. Branch 1 und Zero 1 ergibt PCSrc 1. Der Offset ist relativ zur aktuellen Branch-Adresse, nicht zu PC plus 4. Lehrwerte: PC gleich 0x100, Offset plus 12. Genommenes Ziel 0x10C, nicht genommen 0x104. Das sind illustrative Adressen, keine Ripes-Startadresse. bne braucht Branch und nicht Zero. Im Ripes-Single-Cycle-Modell vergleicht ein eigener Block die Register.</p>
<p>Kontrollfrage: Wohin springt beq bei Gleichheit in diesem Beispiel? Nach 0x10C. Als Nächstes fassen wir die Signale zusammen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zwischenstand-der-tabelle" class="slide level2">
<h2>Zwischenstand der Tabelle</h2>
<ul>
<li>Weichen und Enable-Pins für den Chip unter Kontrolle</li>
<li>Datenverkehr und Speicherblockaden sind spezifiziert</li>
<li>Noch offen: Was genau soll die ALU tun?</li>
<li>Main Control hat bisher nur die groben Pfade organisiert</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Signal</th>
<th>Funktion</th>
<th>Bauteil</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ALUSrc</code></td>
<td>0=Reg, 1=Imm</td>
<td>MUX vor ALU</td>
</tr>
<tr class="even">
<td><code>MemtoReg</code></td>
<td>0=ALU, 1=RAM</td>
<td>MUX vor Write-Back</td>
</tr>
<tr class="odd">
<td><code>RegWrite</code></td>
<td>1=Schreiben</td>
<td>Register-File-Pin</td>
</tr>
<tr class="even">
<td><code>MemRead</code> / <code>MemWrite</code></td>
<td>1=Aktiv</td>
<td>RAM-Pins</td>
</tr>
<tr class="odd">
<td><code>Branch</code></td>
<td>1=Sprungbereit</td>
<td>AND vor PC</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Tabelle zeigt ALUSrc, MemtoReg, RegWrite, MemRead, MemWrite und Branch. ALUOp fehlt noch. MemRead und MemWrite sind zwei Signale. Branch ist nicht der fertige PC-Selektor. Zustand ändern RegWrite, MemWrite und die PC-Fortschaltung. ALUSrc und MemtoReg wählen nur Quellen, MemtoReg aber nur beobachtbar bei RegWrite gleich 1.</p>
<p>Kontrollfrage: Welches Signal schreibt den Datenspeicher? MemWrite. Nun wird die konkrete ALU-Operation bestimmt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-fehlende-alu-signal" class="slide level2">
<h2>Das fehlende ALU-Signal</h2>
<ul>
<li>Warum kein simples <code>ALU_Addition</code>-Signal in der Main Control?</li>
<li>Problem: der 7-Bit-Opcode</li>
<li><code>add</code> und <code>sub</code> teilen denselben Opcode <code>0110011</code></li>
<li>Main Control sieht nur die Familie — nicht Plus vs.&nbsp;Minus</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb12-1"><a aria-label="1"></a>; Main Control sieht nur 0110011:</span>
<span id="cb12-2"><a aria-label="2"></a>add t0, t1, t2</span>
<span id="cb12-3"><a aria-label="3"></a>sub t0, t1, t2</span>
<span id="cb12-4"><a aria-label="4"></a>and t0, t1, t2</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>add, sub und and können dieselben Registeroperanden und denselben Opcode 0110011 haben. Die Ergebnisse unterscheiden sich, weil funct-Felder verschieden sind. Ein einzelnes Addition-ja-nein-Signal reicht für das Subset nicht. Die Detaildecodierung ist eine Modellzerlegung, keine ISA-Vorschrift.</p>
<p>Kontrollfrage: Haben add und and denselben Opcode? Ja. Die nächste Folie quantifiziert eine naive Eingabetabelle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-problem-mit-r-types" class="slide level2">
<h2>Das Problem mit R-Types</h2>
<ul>
<li>Opcode, <code>funct3</code> und <code>funct7</code> sind zusammen viele Eingangsbits</li>
<li>Eine naive Tabelle hätte <span class="math inline">\(2^{17} = 131072\)</span> Zeilen</li>
<li>Die synthetisierte Schaltung listet diese Zeilen nicht physisch auf</li>
<li>Don’t-Care und die Zweistufigkeit verkleinern die Beschreibung, nicht per se die gemessene Fläche</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Input[17 Bit Input] --&gt;|131000 Kombinationen| CPU[Gigantisches Steuerwerk]
  style CPU fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Input fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Sieben Opcode-Bits, drei funct3-Bits und sieben funct7-Bits sind 17 Bits. 2 hoch 17 ist 131072 Kombinationen einer naiv vollständigen Tabelle. Das ist nicht die physische Schaltung und kein Beleg, dass die Taktfrequenz einbricht. Nicht jede Kombination ist ein unterstützter Befehl. Strukturierte Decoder nutzen gemeinsame Bedingungen. Kosten hängen von der Umsetzung ab.</p>
<p>Kontrollfrage: Sind 131072 Zeilen die Gatterzahl? Nein. Die nächste Zerlegung trennt Familie und Funktionsbits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="alu-control-zweistufige-decodierung" class="title-slide slide level1 center">
<h1>ALU Control (Zweistufige Decodierung)</h1>
<aside class="notes">
<p>ALU bedeutet Arithmetic Logic Unit. Decodierung ordnet Bitmuster einer Operation zu. Die offene Frage lautet: Wie verbindet man die grobe Familie mit den feinen Funktionsbits, ohne alles in einer unübersichtlichen Tabelle zu vermischen? Die Antwort ist eine Modellzerlegung, keine ISA-Pflicht.</p>
<p>Kontrollfrage: Schreibt RISC-V ALUOp vor? Nein. Die nächste Folie führt diese Brücke ein.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="teile-und-herrsche" class="slide level2">
<h2>Teile und Herrsche</h2>
<ul>
<li>Ausweg aus der gigantischen Wahrheitstabelle</li>
<li>Delegation von Verantwortung</li>
<li>2-Bit-Signal <code>ALUOp</code> als Brücke zwischen den Abteilungen</li>
<li>Kleine ALU Control Unit als Detail-Spezialist</li>
<li>Auswertung von <code>funct3</code> und <code>funct7</code></li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Main[Main Control] --&gt;|ALUOp| Sub[ALU Control]
  Sub --&gt;|4-Bit Kommando| ALU((ALU))
  style Main fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Sub fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style ALU fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Die Main Control bildet aus dem Opcode die Kategorie ALUOp. Die ALU Control bildet daraus und aus den Funktionsbits das konkrete Kommando. Bei lw verlangt die Main Control Addition. Die ALU Control muss dann die Registerfunktionsbits nicht noch einmal als Operationsentscheid lesen. Zwei Boxen mit Bitbreiten machen die Zuständigkeit sichtbar. Eine einzige große Tabelle ist keine notwendige physische Alternative.</p>
<p>Kontrollfrage: Muss lw die funct7-Bits der R-Types auswerten? Für die bereits erkannte Additionsaufgabe nein. Die nächste Folie zeigt die Ein- und Ausgänge.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-lösung-zweistufige-kontrolle" class="slide level2">
<h2>Die Lösung: Zweistufige Kontrolle</h2>
<ul>
<li>Logik in zwei separate Boxen</li>
<li>Stufe 1 (Main Control): 7-Bit-Opcode; MUXe und Speicher; sendet <code>ALUOp</code></li>
<li>Stufe 2 (ALU Control): nimmt <code>ALUOp</code>, liest <code>funct3</code>/<code>funct7</code>, finales ALU-Kommando</li>
<li>Zwei kleine Schaltungen sind schneller und kleiner als eine gigantische</li>
</ul>
<aside class="notes">
<p>Zwei kleine Schaltungen sind nicht automatisch schneller oder kleiner. Eine zusätzliche Stufe kann Laufzeit beitragen. Der Nutzen hier ist eine prüfbare Zuständigkeit. ALUOp ist ein Zweibitbus. ALUControl ist das vierbitige Kurskommando. Der Weg ist Opcode, Main Control, ALUOp, ALU Control, plus getrennt zugeführte Funktionsfelder.</p>
<p>Kontrollfrage: Ist ALUOp schon der Addierbefehl? Nein. Die nächste Folie definiert die vier Kategorien.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-signal-aluop-2-bit" class="slide level2">
<h2>Das Signal ALUOp (2 Bit)</h2>
<ul>
<li>Verlässt die Main Control Richtung ALU Control</li>
<li>2 Bit — vier grobe Zustände</li>
<li>Kategorisiert die Aufgabe der ALU</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>ALUOp</th>
<th>Bedeutung</th>
<th>Befehlstypen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>00</code></td>
<td>ALU muss addieren (unbedingt)</td>
<td><code>lw</code>, <code>sw</code>, <code>addi</code></td>
</tr>
<tr class="even">
<td><code>01</code></td>
<td>ALU muss subtrahieren (Vergleich)</td>
<td><code>beq</code></td>
</tr>
<tr class="odd">
<td><code>10</code></td>
<td>ALU muss rechnen (funct lesen)</td>
<td>R-Type</td>
</tr>
<tr class="even">
<td><code>11</code></td>
<td>Reserve / ungenutzt</td>
<td>-</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>ALUOp 00 verlangt ADD für lw, sw und addi. 01 verlangt im Lehrmodell SUB für den beq-Vergleich. 10 lässt die unterstützte Registeroperation aus den funct-Feldern bestimmen. 11 ist unbenutzt. Ungültige Eingaben dürfen daraus kein beliebiges Schreiben ableiten. addi mit Immediate minus 5 hat instr[30] gleich 1, weil dieses Bit zum Immediate gehört, und muss trotzdem addieren. Das Maschinenwort addi t0, x0, minus 5 ist als 0xFFB00293 zu prüfen. Diese Fassung hat den Assembler nicht ausgeführt.</p>
<p>Kontrollfrage: Darf Bit 30 bei addi die Subtraktion wählen? Nein. Die ALU Control übersetzt die Kategorie.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-kleine-alu-control-unit" class="slide level2">
<h2>Die kleine ALU Control Unit</h2>
<ul>
<li>Eingänge: <code>ALUOp</code> (2), <code>funct3</code> (3), relevantes <code>funct7</code>-Bit (1)</li>
<li><code>funct7</code> nur auswerten, wenn nötig (R-Type)</li>
<li>Ausgang: 4-Bit-Steuerwort in die ALU</li>
<li>Definiert die Verschaltung: Plus, Minus, AND, OR</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  ALUOp[ALUOp 2 Bit] --&gt; Box((ALU Control))
  F3[funct3] --&gt; Box
  F7[funct7 Bit30] --&gt; Box
  Box --&gt;|4 Bit| ALU((ALU))
  style Box fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style ALUOp fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style F3 fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style F7 fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style ALU fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Die vereinfachte Box sieht sechs Bits: zwei ALUOp, drei funct3 und instr[30]. Das ersetzt nicht die Legalitätsprüfung über Opcode und vollständiges funct7. Nur bei Bedarf auswerten darf illegale Kombinationen nicht als gültige Operationen durchlassen. Der Ausgang hat vier Bits nach der Kurskonvention 0000 AND, 0001 OR, 0010 ADD und 0110 SUB.</p>
<p>Kontrollfrage: Sind diese vier Bits RISC-V-Opcodes? Nein. Die einfachste Kategorie erzwingt Addition.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fall-1-aluop-00-load-store-addi" class="slide level2">
<h2>Fall 1: ALUOp = 00 (Load, Store, addi)</h2>
<ul>
<li>Chef funkt <code>00</code> — <code>lw</code> oder <code>sw</code></li>
<li>Hardware muss Base + Offset addieren</li>
<li>ALU Control ignoriert funct-Bits (<span class="math inline">\(X\)</span>)</li>
<li>Sendet hart verdrahtet ADD (<code>0010</code>) an die ALU</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb13-1"><a aria-label="1"></a>WENN ALUOp == 00:</span>
<span id="cb13-2"><a aria-label="2"></a>  Sende ADD an die ALU</span>
<span id="cb13-3"><a aria-label="3"></a>  (funct-Felder irrelevant)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>ALUOp 00 erzwingt Addition für bereits gültig erkanntes lw, sw und addi. Bei lw und sw entsteht eine Adresse, bei addi ein Registerwert. Der Immediate wird vorzeichenerweitert. Lehrwerte: Basis 0x2000 plus Offset 4 ergibt 0x2004. addi von 7 und minus 5 ergibt 2. Die funct-Felder entscheiden in dieser Kategorie nicht noch einmal die Operation.</p>
<p>Kontrollfrage: Addiert ALUOp 00 auch bei einem gesetzten Bit 30 von addi? Ja. Kategorie 01 nutzt im Lehrmodell eine andere Funktion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fall-2-aluop-01-beq-vergleich-im-lehrmodell" class="slide level2">
<h2>Fall 2: ALUOp = 01 (beq-Vergleich im Lehrmodell)</h2>
<ul>
<li>Chef funkt <code>01</code> — bedingter Sprung</li>
<li>Zwei Register subtrahieren, um Zero zu füttern</li>
<li>funct-Bits wieder ignoriert</li>
<li>Sendet SUB (<code>0110</code>) an die ALU</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb14-1"><a aria-label="1"></a>WENN ALUOp == 01:</span>
<span id="cb14-2"><a aria-label="2"></a>  Sende SUB an die ALU</span>
<span id="cb14-3"><a aria-label="3"></a>  (Zero-Flag bei Gleichheit)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Der Untertitel gilt für den beq-Vergleich im Lehrmodell, nicht für jeden Branch und nicht für Ripes. 9 minus 9 ist 0, Zero wird 1. 9 minus 4 ist 5, Zero bleibt 0. Die ALU vergleicht. Ein separater Addierer bildet das Ziel PC plus Offset. In Ripes übernimmt ein eigener Vergleicher die Register. Der vollständige Decoder darf die Branch-Art nicht generell ignorieren.</p>
<p>Kontrollfrage: Berechnet die ALU hier das Sprungziel? Im Lehrmodell nein. R-Type braucht eine funktionsabhängige Auswahl.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fall-3-aluop-10-r-type" class="slide level2">
<h2>Fall 3: ALUOp = 10 (R-Type)</h2>
<ul>
<li>Chef funkt <code>10</code> — Detail-Arbeit</li>
<li>ALU Control erwacht und liest die funct-Felder</li>
<li>Unterscheidung: <code>add</code>, <code>sub</code>, <code>and</code>, …</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb15-1"><a aria-label="1"></a>Opcode 0110011, ALUOp = 10</span>
<span id="cb15-2"><a aria-label="2"></a>-&gt; funct3 / funct7 scannen</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>funct3 und funct7 unterscheiden die unterstützten Registeroperationen. Dieselben Quellwerte können add, sub, and oder or durchlaufen. Die Pfadauswahlen bleiben gleich, das ALU-Ergebnis nicht. Erwacht ist eine Metapher und bedeutet nicht, dass alle anderen Gatter physisch abgeschaltet sind. Voraussetzung sind legale Encodings des Subsets.</p>
<p>Kontrollfrage: Ändert or gegenüber add den Wert von ALUSrc? Nein. Zuerst wird funct3 gelesen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="funct3-als-wegweiser" class="slide level2">
<h2>funct3 als Wegweiser</h2>
<ul>
<li>Bei <code>ALUOp = 10</code> ist <code>funct3</code> der primäre Wegweiser</li>
<li><code>funct3 = 111</code> — bitweises AND</li>
<li><code>funct3 = 110</code> — bitweises OR</li>
<li><code>funct3 = 000</code> — Arithmetik (Plus oder Minus?)</li>
<li>Bei <code>000</code> reicht funct3 noch nicht — nächste Stufe</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>ALUOp</th>
<th>funct3</th>
<th>Aktion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>10</code></td>
<td><code>111</code></td>
<td>AND</td>
</tr>
<tr class="even">
<td><code>10</code></td>
<td><code>110</code></td>
<td>OR</td>
</tr>
<tr class="odd">
<td><code>10</code></td>
<td><code>000</code></td>
<td>Plus oder Minus? → Bit 30</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>funct3 liegt in den Bits 14 bis 12. 000 ist der Addier-/Subtrahierfall, 110 ist or, 111 ist and. Bitweise AND und OR verknüpfen gleiche Positionen. Ein kurzes Beispiel 0x0F und 0xA5 ist nur ein Ausschnitt der 32-Bit-Operation. 000 allein unterscheidet add und sub nicht. Dieselben funct3-Codes bedeuten in anderen Opcode-Familien nicht dieselbe Operation.</p>
<p>Kontrollfrage: Reicht funct3 gleich 000 für sub? Nein. funct7 löst den Unterschied.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="funct7-als-letzter-schalter" class="slide level2">
<h2>funct7 als letzter Schalter</h2>
<ul>
<li>Nur wenn <code>ALUOp = 10</code> und <code>funct3 = 000</code></li>
<li>Relevant: Bit 30 der Instruktion (in <code>funct7</code>)</li>
<li>Bit 30 = 0 — <code>add</code></li>
<li>Bit 30 = 1 — <code>sub</code></li>
<li>Rätsel entschlüsselt</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb16-1"><a aria-label="1"></a>add t0, t1, t2   # Bit 30 = 0  (funct7 = 0000000)</span>
<span id="cb16-2"><a aria-label="2"></a>sub t0, t1, t2   # Bit 30 = 1  (funct7 = 0100000)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>add hat funct7 gleich 0000000, sub gleich 0100000. Der sichtbare Unterschied dieser beiden Encodings bei gleichen Registern ist Bit 30. Die Aussage gilt nicht für beliebige Bitmuster. Ein MUL der M-Erweiterung kann Opcode 0110011 und funct3 000 haben, aber funct7 0000001. Ein naiver Blick nur auf Bit 30 würde es fälschlich als add lesen. Bei Immediate-Befehlen ist Bit 30 kein funct7-Bit.</p>
<p>Kontrollfrage: Darf jedes Muster mit Bit 30 gleich 0 als add gelten? Nein. Der Decoder erzeugt daraus das Kurs-Steuerwort.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-4-bit-alu-kommando" class="slide level2">
<h2>Das 4-Bit-ALU-Kommando</h2>
<ul>
<li>Ergebnis der ALU Control: 4 Steuerbits in die Haupt-ALU</li>
<li>Standardcodierung nach Patterson/Hennessy</li>
<li>ALU-Hardware schaltet stur bei diesen Bitmustern</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>4-Bit ALU-Kommando</th>
<th>Hardware-Reaktion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>0000</code></td>
<td>bitweises AND</td>
</tr>
<tr class="even">
<td><code>0001</code></td>
<td>bitweises OR</td>
</tr>
<tr class="odd">
<td><code>0010</code></td>
<td>ADDITION</td>
</tr>
<tr class="even">
<td><code>0110</code></td>
<td>SUBTRAKTION</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die vier Codes sind die Kurskonvention nach dem Lehrbuchmuster, nicht ein RISC-V-Standard. 0000 ist AND, 0001 OR, 0010 ADD, 0110 SUB. Eine mögliche ALU bildet SUB, indem sie den zweiten Operanden invertiert und den ersten Carry auf eins setzt. Das ist ein Implementierungsbeispiel. ALUOp und ALUControl bleiben zwei Tabellen.</p>
<p>Kontrollfrage: Ist 0110 der Opcode von sub? Nein. Die nächste Folie fasst die Zuordnung zusammen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-wahrheitstabelle-der-alu-control" class="slide level2">
<h2>Die Wahrheitstabelle der ALU Control</h2>
<ul>
<li>Matrix der Experten-Box — als Gatter verlötet</li>
<li><span class="math inline">\(X\)</span> rettet vor unnötigen Gattern bei Load/Store/Branch</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 41%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>ALUOp</th>
<th>Bit 30</th>
<th>funct3</th>
<th>Bedeutung im Lehrsubset</th>
<th>ALU-Output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>00</code></td>
<td><span class="math inline">\(X\)</span></td>
<td><span class="math inline">\(X\)</span></td>
<td><code>lw</code> / <code>sw</code> / <code>addi</code>, legal erkannt</td>
<td><code>0010</code> (ADD)</td>
</tr>
<tr class="even">
<td><code>01</code></td>
<td><span class="math inline">\(X\)</span></td>
<td><span class="math inline">\(X\)</span></td>
<td><code>beq</code> im Lehrmodell</td>
<td><code>0110</code> (SUB)</td>
</tr>
<tr class="odd">
<td><code>10</code></td>
<td><code>0</code></td>
<td><code>000</code></td>
<td><code>add</code>, funct7 <code>0000000</code></td>
<td><code>0010</code> (ADD)</td>
</tr>
<tr class="even">
<td><code>10</code></td>
<td><code>1</code></td>
<td><code>000</code></td>
<td><code>sub</code>, funct7 <code>0100000</code></td>
<td><code>0110</code> (SUB)</td>
</tr>
<tr class="odd">
<td><code>10</code></td>
<td><span class="math inline">\(X\)</span></td>
<td><code>111</code></td>
<td><code>and</code>, funct7 <code>0000000</code></td>
<td><code>0000</code> (AND)</td>
</tr>
<tr class="even">
<td><code>10</code></td>
<td><span class="math inline">\(X\)</span></td>
<td><code>110</code></td>
<td><code>or</code>, funct7 <code>0000000</code></td>
<td><code>0001</code> (OR)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Tabelle gilt für legale Eingaben des Lehrsubsets. X bei Bit 30 oder funct3 bedeutet: für diese bereits erkannte Kategorie wird das Bit nicht als weiterer Operationsentscheid gebraucht. Es ersetzt keine Prüfung des ganzen Encodings. ALUOp 00 ergibt 0010 für lw, sw und addi. 01 ergibt 0110 für beq im Lehrmodell. 10 mit funct3 000 und Bit 30 gleich 0 ist add, mit Bit 30 gleich 1 sub. funct3 111 ist and mit 0000. funct3 110 ist or mit 0001. addi t0, x0, minus 5 bleibt Addition, obwohl Bit 30 eins ist. or von 0x0F und 0xA5 ergibt im unteren Byte 0xAF. ALUOp 11 ist unbenutzt.</p>
<p>Kontrollfrage: Welche ALUControl-Zeile hat or? 0001. Danach bewerten wir die Zerlegung als Beschreibung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-zweistufig-effizienz" class="slide level2">
<h2>Warum zweistufig? (Effizienz)</h2>
<ul>
<li>Zwei getrennte Beschreibungen: <span class="math inline">\(2^7 = 128\)</span> und <span class="math inline">\(2^6 = 64\)</span> Eingabekombinationen</li>
<li>Das ist keine Messung von Fläche, Strom oder Takt</li>
<li>Die 6-Bit-Tabelle ersetzt keine vollständige Legalitätsprüfung</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  A[130000 Zeilen] -.-&gt;|Delegation| B[128 Zeilen]
  B -.-&gt; C[64 Zeilen]
  style B fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style C fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style A fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>2 hoch 7 ist 128, 2 hoch 6 ist 64. Zusammen sind das 192 Eingabekombinationen zweier getrennter Beschreibungen. Das ist kein Flächen- oder Taktvergleich mit 2 hoch 17. Die kleine Tabelle enthält einen reduzierten Eingang und prüft nicht jedes illegale funct7. Der Vorteil ist Übersicht, gemeinsame Regeln und nachvollziehbare Verifikation.</p>
<p>Kontrollfrage: Beweisen 192 Zeilen einen höheren Takt? Nein. Das Zwischenfazit begrenzt, was fertig ist.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-steuerkonzept-für-unser-lehrsubset-steht" class="slide level2">
<h2>Das Steuerkonzept für unser Lehrsubset steht</h2>
<ul>
<li>Ausgewählte Pfade und sieben Hauptsignale sind spezifiziert</li>
<li>Nicht die vollständige RV32I-Implementierung</li>
<li>Als Nächstes: die Meistertabelle für add, lw, sw und beq</li>
</ul>
<aside class="notes">
<p>Bekannt sind die ausgewählten Pfade und Steuersignale des Lehrsubsets. Eine vollständige ISA-Implementierung, ein physischer Chip und Messwerte stehen damit nicht fest. Es fehlen unter anderem weitere ALU-Operationen, Bytezugriffe, Sprünge mit Rücksprungadresse und die Behandlung nicht unterstützter Encodings. Offen bleibt die konsistente Haupttabelle.</p>
<p>Kontrollfrage: Ist die CPU damit vollständig gebaut? Nein. Der nächste Abschnitt führt die Signale pro Instruktion zusammen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="signal-trace-die-meistertabelle" class="title-slide slide level1 center">
<h1>Signal-Trace (Die Meistertabelle)</h1>
<aside class="notes">
<p>Ein Trace verfolgt Daten und Signale Schritt für Schritt. Dieselbe Befehlswirkung wird in die sieben Hauptsignale übersetzt. Die Matrix gehört zum Lehrmodell. Ripes wird später funktional abgeglichen, nicht bitweise gleichgesetzt.</p>
<p>Kontrollfrage: Ist der Trace eine Ripes-Portliste? Nein. Die nächste Folie beschreibt die Herleitungsmethode.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-meistertabelle" class="slide level2">
<h2>Die Meistertabelle</h2>
<ul>
<li>Alle Hebel in einer Matrix</li>
<li>Deduktiv herleiten statt auswendig lernen</li>
<li>Trace durch R-Type, Load, Store und Branch</li>
<li>Don’t Cares optimieren die Tabelle</li>
<li>Referenzblatt für die Ripes-Laborsimulation</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph TD
  Instruktion --&gt; Trace[Deduktiver Trace]
  Trace --&gt; Tabelle[Master Wahrheitstabelle]
  style Tabelle fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Instruktion fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Trace fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Die Reihenfolge lautet: Quellen, ALU-Aufgabe, Speicherzugriff, Write-Back, PC-Änderung. Ein X braucht eine Begründung. Die Tabelle ist nicht die unveränderte Ripes-Portbelegung. Eine leere Zeile fragt: Woher kommen die Operanden, was rechnet die ALU, wer schreibt, und ändert sich der PC abweichend von plus 4?</p>
<p>Kontrollfrage: Darf ein X ohne Begründung stehen? Nein. Das Arbeitsblatt legt die Spalten fest.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-finale-matrix-das-skelett" class="slide level2">
<h2>Die finale Matrix (Das Skelett)</h2>
<ul>
<li>Control-Tabelle nach Patterson/Hennessy</li>
<li>Ausfüllen durch logisches Denken, nicht auswendig</li>
<li>Vier Befehlsfamilien (Zeilen), acht Ausgangssignale (Spalten)</li>
<li>Datenpfad aus Einheit 5 im geistigen Auge behalten</li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R-Type</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>lw</code></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>sw</code></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>beq</code></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Sieben Hauptsignale ergeben acht Bits, weil ALUOp zwei Bit hat. ALUOp1 ist das höhere, ALUOp0 das niedrige Bit. Vier Zeilengruppen sind ausgewählte Befehle, keine vollständigen Familien. R-Type meint add, sub, and und or. Die Herleitung fragt für jede Spalte nach der beobachtbaren Wirkung.</p>
<p>Kontrollfrage: Sind es acht unabhängige Main-Control-Ausgänge? Nein, sieben Namen und acht Bits. Der erste Trace beginnt mit add.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-r-type-add-alusrc" class="slide level2">
<h2>Trace: R-Type (<code>add</code>) — ALUSrc</h2>
<ul>
<li>Zeile für R-Type (Opcode <code>0110011</code>)</li>
<li>Womit rechnet die ALU? Mit dem zweiten Register (<code>rs2</code>)</li>
<li>MUX vor der ALU schaltet das Register-Kabel durch</li>
<li><code>ALUSrc = 0</code></li>
<li>ImmGen bei R-Type abgeklemmt</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Reg[Register RD2] --&gt;|0| MUX{ALUSrc = 0}
  Imm[Immediate] --&gt;|1| MUX
  MUX --&gt;|Register| ALU((ALU))
  style MUX fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Reg fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Imm fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style ALU fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>add t0, t1, t2 mit t1 gleich 7 und t2 gleich 3. rs1 und rs2 sind die Adressfelder, 7 und 3 die gelesenen Werte. ALUSrc gleich 0 wählt RD2 gleich 3. Der ImmGen muss nicht physisch abgeschaltet sein. Sein Wert wird für diesen ALU-Eingang nicht gewählt. Das Ergebnis der Addition wird 10.</p>
<p>Kontrollfrage: Sieht die ALU die Registernummern oder die Werte? Die Werte. Das Ergebnis muss ins Zielregister.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-r-type-speichern" class="slide level2">
<h2>Trace: R-Type — Speichern</h2>
<ul>
<li>Ergebnis verlässt die ALU und muss gespeichert werden</li>
<li>Schreiben wir ein Register (<code>rd</code>)? Ja → <code>RegWrite = 1</code></li>
<li>Welches Signal speichern? Das ALU-Ergebnis</li>
<li>MemtoReg klemmt den RAM ab → <code>MemtoReg = 0</code></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb17-1"><a aria-label="1"></a>R-Type:</span>
<span id="cb17-2"><a aria-label="2"></a>RegWrite = 1</span>
<span id="cb17-3"><a aria-label="3"></a>MemtoReg = 0</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Speichern meint hier das Register-Write-Back, nicht den Datenspeicher. MemtoReg gleich 0 führt die 10 zum Datenport von t0. RegWrite gleich 1 erlaubt die Übernahme an der Modellflanke. Der vorherige Inhalt von t0 ist beliebig, solange er vor dem Befehl nicht gelesen wird. Der Datenspeicher wird nicht beschrieben.</p>
<p>Kontrollfrage: Welcher Wert steht nach der Flanke in t0? 10. Die übrigen Signale schließen die Zeile ab.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-r-type-ram-und-aluop" class="slide level2">
<h2>Trace: R-Type — RAM und ALUOp</h2>
<ul>
<li>Benutzen wir den RAM? Nein → <code>MemRead = 0</code>, <code>MemWrite = 0</code></li>
<li>Bedingter Sprung? Nein → <code>Branch = 0</code></li>
<li>ALU-Kommando: Entscheidung delegieren → <code>ALUOp = 10</code></li>
<li>Erste Zeile der Meistertabelle ist komplett</li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R-Type</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Zeile ist ALUSrc 0, MemtoReg 0, RegWrite 1, MemRead 0, MemWrite 0, Branch 0, ALUOp 10. RAM bedeutet Random Access Memory. Lesen und Schreiben des Datenspeichers sind aus. Branch gleich 0 wählt den sequenziellen PC-Pfad, im Modell ohne C plus 4. ALUOp 10 und die Felder von add ergeben ALUControl 0010. Der Registerzustand ändert sich, der Speicher nicht.</p>
<p>Kontrollfrage: Welches ALUOp hat add? 10. Load verwendet Immediate und Speicher-Write-Back.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-i-type-lw-alusrc" class="slide level2">
<h2>Trace: I-Type (<code>lw</code>) — ALUSrc</h2>
<ul>
<li>Load Word (Opcode <code>0000011</code>)</li>
<li>Adresse = Base + Offset → Immediate nötig</li>
<li>ALUSrc schaltet ImmGen durch</li>
<li><code>ALUSrc = 1</code></li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Reg[Register RD2] --&gt;|0| MUX{ALUSrc = 1}
  Imm[Immediate Offset] --&gt;|1| MUX
  MUX --&gt;|Immediate| ALU((ALU))
  style MUX fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Reg fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Imm fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style ALU fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Lehrwerte, nicht ein vorhandener Simulatorzustand: s1 gleich 0x2000, lw t0, 4(s1), Speicherwort an 0x2004 gleich 37. ALUSrc gleich 1 wählt den vorzeichenerweiterten Offset plus 4. Die ALU bildet die Adresse 0x2004. Das ist noch nicht das geladene Wort.</p>
<p>Kontrollfrage: Was liegt nach der Addition an der Speicheradresse an? 0x2004. Der Speicher liefert nun den Inhalt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-i-type-lw-ram" class="slide level2">
<h2>Trace: I-Type (<code>lw</code>) — RAM</h2>
<ul>
<li>Daten auslesen? Ja → <code>MemRead = 1</code></li>
<li><code>MemWrite = 0</code> (Schutz)</li>
<li>Letzte Weiche: RAM-Daten zum Register → <code>MemtoReg = 1</code></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb18-1"><a aria-label="1"></a>lw:</span>
<span id="cb18-2"><a aria-label="2"></a>MemRead  = 1</span>
<span id="cb18-3"><a aria-label="3"></a>MemWrite = 0</span>
<span id="cb18-4"><a aria-label="4"></a>MemtoReg = 1</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>MemRead gleich 1 liefert in diesem Modell den Wert 37. MemWrite gleich 0 lässt den Speicher unverändert. MemtoReg gleich 1 wählt 37 statt der Adresse 0x2004. Ein Word ist hier 32 Bit. Die Lesezugriffsfreigabe ist nicht dasselbe wie ein bestimmter elektrischer Ausgangszustand. Adresse und Daten sind verschieden beschriftet.</p>
<p>Kontrollfrage: Was darf nicht nach t0 geschrieben werden? Die Adresse 0x2004. Die Schreibfreigabe vollendet den Load.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-i-type-lw-reg-und-aluop" class="slide level2">
<h2>Trace: I-Type (<code>lw</code>) — Reg und ALUOp</h2>
<ul>
<li>In <code>rd</code> schreiben? Ja → <code>RegWrite = 1</code></li>
<li>Sprung? Nein → <code>Branch = 0</code></li>
<li>ALU muss Adresse addieren → <code>ALUOp = 00</code></li>
<li>Zweite Zeile steht</li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><code>lw</code></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Zeile ist 1, 1, 1, 1, 0, 0, 00. RegWrite gleich 1 schreibt t0. ALUOp 00 hat die Adresse addiert. Nach der Übernahme ist t0 gleich 37. s1 und der Speicher bleiben gleich. Der PC läuft im Modell um vier Byte weiter. Wäre rd gleich x0, bliebe x0 null.</p>
<p>Kontrollfrage: Welches MemtoReg hat lw? 1. Store teilt die Adressbildung, nicht das Register-Write-Back.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-s-type-sw" class="slide level2">
<h2>Trace: S-Type (<code>sw</code>)</h2>
<ul>
<li>Store Word (Opcode <code>0100011</code>)</li>
<li>Adresse wieder Base + Offset → <code>ALUSrc = 1</code></li>
<li>In den RAM schreiben? Ja → <code>MemWrite = 1</code></li>
<li><code>MemRead = 0</code> im Modell: dieser Zugriff liest nicht</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb19-1"><a aria-label="1"></a>sw:</span>
<span id="cb19-2"><a aria-label="2"></a>ALUSrc   = 1</span>
<span id="cb19-3"><a aria-label="3"></a>MemWrite = 1</span>
<span id="cb19-4"><a aria-label="4"></a>MemRead  = 0</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>sw t1, 4(s1) mit s1 gleich 0x2000, t1 gleich 10 und bisherigem Speicherinhalt 37. ALUSrc gleich 1 und ALUOp 00 erzeugen die Adresse 0x2004. Die Store-Daten 10 kommen getrennt aus rs2. MemWrite gleich 1 und MemRead gleich 0 sind die Zugriffsregeln. Beide Pfade bleiben in derselben Abbildung sichtbar.</p>
<p>Kontrollfrage: Welcher Wert wird gespeichert? 10, nicht 37. Das nicht benötigte Write-Back erklärt das X.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-s-type-sw-dont-cares" class="slide level2">
<h2>Trace: S-Type (<code>sw</code>) — Don’t Cares</h2>
<ul>
<li>Werkbank-überschreiben? Nein → <code>RegWrite = 0</code></li>
<li>MemtoReg bei geschlossener Tür wirkungslos → <span class="math inline">\(X\)</span></li>
<li>ALU wieder Adressaddition → <code>ALUOp = 00</code></li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><code>sw</code></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(X\)</span></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Zeile ist 1, X, 0, 0, 1, 0, 00. Nach der Übernahme enthält 0x2004 den Wert 10. Die Register bleiben unverändert. MemtoReg darf 0 oder 1 sein, weil RegWrite 0 ist. MemWrite bleibt zwingend 1. S-Type hat kein rd. Das X gilt für dieses Modell und ist keine Freiheit für die Speichersteuersignale.</p>
<p>Kontrollfrage: Darf MemWrite hier X sein? Nein. Branch hat ebenfalls kein Register-Write-Back, ändert aber den PC anders.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-b-type-beq" class="slide level2">
<h2>Trace: B-Type (<code>beq</code>)</h2>
<ul>
<li>Branch (Opcode <code>1100011</code>)</li>
<li>Vergleich zweier Register → <code>ALUSrc = 0</code></li>
<li>Kein Speichern in RAM oder Register File</li>
<li><code>MemWrite = 0</code>, <code>MemRead = 0</code>, <code>RegWrite = 0</code></li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  BType[Branch] --&gt;|0| RegWrite
  BType --&gt;|0| MemWrite
  BType --&gt;|0| MemRead
  style BType fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style RegWrite fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style MemWrite fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style MemRead fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>RegWrite, MemRead und MemWrite sind 0. Der PC wird trotzdem aktualisiert. Zwei Fälle: gleiche Register ergeben Zero 1, ungleiche Zero 0. ALUSrc gleich 0 gilt für den SUB-Vergleich im Lehrmodell, nicht automatisch in Ripes. PC 0x100 und Offset plus 12 bleiben das Zahlenbeispiel. Enable null heißt nicht, dass kein Zustandselement weiterschaltet.</p>
<p>Kontrollfrage: Bleibt der PC bei beq stehen? Nein. Bedingung und Freigabe bestimmen den nächsten PC.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trace-b-type-beq-control-und-x" class="slide level2">
<h2>Trace: B-Type (<code>beq</code>) — Control und <span class="math inline">\(X\)</span></h2>
<ul>
<li>Branch-Weiche vor dem PC freigeben → <code>Branch = 1</code></li>
<li>MemtoReg wieder wirkungslos (<code>RegWrite = 0</code>) → <span class="math inline">\(X\)</span></li>
<li>ALU: zwingende Subtraktion → <code>ALUOp = 01</code></li>
<li>Meistertabelle vollständig deduziert</li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><code>beq</code></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><span class="math inline">\(X\)</span></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Zeile des Lehrmodells ist 0, X, 0, 0, 0, 1, 01. Bei Gleichheit ist PCSrc 1 und das Ziel 0x10C. Bei Ungleichheit ist PCSrc 0 und der nächste PC 0x104. Branch bleibt in beiden Fällen 1. MemtoReg gleich X hängt an RegWrite gleich 0, nicht an der Branch-Bedingung. Der SUB-Vergleich und die Zieladdition sind getrennt.</p>
<p>Kontrollfrage: Ist Branch bei einem nicht genommenen beq null? Nein. Die vier Zeilen werden zusammengeführt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-ausgefüllte-meistertabelle" class="slide level2">
<h2>Die ausgefüllte Meistertabelle</h2>
<ul>
<li>Referenz des Lehrmodells, nicht eine 1:1-Porttabelle von Ripes</li>
<li><span class="math inline">\(X\)</span> = für diese Wirkung unerheblich, kein Anzeigewert</li>
<li>Die R-Type-Zeile gilt für die unterstützten legalen Operationen add, sub, and, or</li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R-Type</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>lw</code></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>sw</code></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(X\)</span></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>beq</code></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><span class="math inline">\(X\)</span></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>addi</code></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Basiszeilen bleiben: R-Type 0,0,1,0,0,0,10; lw 1,1,1,1,0,0,00; sw 1,X,0,0,1,0,00; beq 0,X,0,0,0,1,01. addi ist die zusätzliche Zeile 1,0,1,0,0,0,00. X ist tabellarische Unerheblichkeit. Die R-Type-Zeile gilt für die legalen unterstützten Operationen. Keine Zelle ist ein Ripes-Bit gleichen Namens. Pro Zeile gilt: Quelle, Operation, Speicher, Write-Back, PC.</p>
<p>Kontrollfrage: Welche Zeile schreibt aus dem Speicher? lw. Der Praxisteil prüft Wirkung und Simulatorstruktur.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="praxis-signal-analyse-in-ripes" class="title-slide slide level1 center">
<h1>Praxis: Signal-Analyse in Ripes</h1>
<aside class="notes">
<p>Ripes ist ein Lehrsimulator für RISC-V, nicht die Hardware dieses Lehrmodells. Die Frage lautet, wie dieselbe ISA-Wirkung bei anderen internen Pfaden erkannt wird. Nötig sind die Modellwahl, das Layout und der Beobachtungszeitpunkt vor der Taktflanke.</p>
<p>Kontrollfrage: Beweist ein Ripes-Kabel unsere Tabellenbits? Es zeigt das Ripes-Modell. Der Vergleich wird ausdrücklich.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vom-papier-in-den-simulator" class="slide level2">
<h2>Vom Papier in den Simulator</h2>
<ul>
<li>Dieselbe ISA-Wirkung, andere interne Pfade</li>
<li>Lehrmodell: ALU subtrahiert zum Vergleich, ein zweiter Addierer bildet das Sprungziel</li>
<li>Ripes-Single-Cycle laut <code>rvss.h</code>: separater Registervergleicher; das ALU-Ergebnis kann das Ziel liefern</li>
<li>Keine Behauptung, die Steuerbits seien identisch</li>
</ul>
<aside class="notes">
<p>Im Lehrmodell subtrahiert die ALU zum Vergleich, und ein zweiter Addierer bildet PC plus Offset. In der offiziellen Ripes-Datei rvss.h hat der Single-Cycle-Prozessor einen separaten Branch-Vergleicher mit den beiden Registerwerten. Das ALU-Ergebnis kann das Sprungziel liefern. Die ALU-Operandenauswahl kann Register, PC und Immediate unterscheiden. Das Write-Back kann zusätzlich PC plus 4 wählen. Befehls- und Datenzugriff sind an denselben zugrunde liegenden Speicher angebunden. Dieselbe ISA-Wirkung bedeutet nicht dieselben Selektorbits. Eine 1:1-Zuordnung gleichnamiger Signale wird nicht behauptet. Diese Fassung hat die Oberfläche nicht ausgeführt.</p>
<p>Kontrollfrage: Bedeutet Branch in Ripes automatisch ALUOp 01? Nein. Das Laborziel ist eine überprüfbare Vorhersage.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-ziel-im-labor" class="slide level2">
<h2>Das Ziel im Labor</h2>
<ul>
<li>Debugger: unerklärliche Registerzustände</li>
<li>Ursache: ABI, Hardware, Tippfehler?</li>
<li>Signalleitungen während des Clock-Ticks lesen</li>
<li>Methode: Befehl ansehen → erwartete 1/0 → Linie prüfen</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb20-1"><a aria-label="1"></a>Ein Ingenieur klickt nicht auf Run und hofft.</span>
<span id="cb20-2"><a aria-label="2"></a>Ein Ingenieur formuliert eine These und verifiziert sie.</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>ABI bedeutet Application Binary Interface. Hier genügen die Alias t0 gleich x5, t1 gleich x6 und t2 gleich x7. Ein unerwarteter Wert kommt oft von fehlender Initialisierung, falscher Instruktion, falschem Modell oder dem falschen Zeitpunkt. Vorgehen: aktuellen PC und decodierte Instruktion lesen, Wirkung vorhersagen, konkrete Ports lesen, Zustand nach genau einem Takt prüfen.</p>
<p>Kontrollfrage: Ist jedes dunkle Kabel ein Hardwarefehler? Nein. Zuerst wird die passende Ansicht eingeordnet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wo-ist-die-control-unit-in-ripes" class="slide level2">
<h2>Wo ist die Control Unit in Ripes?</h2>
<ul>
<li>RV32 Single Cycle wählen, C-Erweiterung aus, Extended-Layout einschalten</li>
<li>Portnamen und Werte ablesen, nicht eine feste Bildschirmposition</li>
<li>Diese Fassung hat die Oberfläche nicht live geprüft; die Struktur folgt der offiziellen Quelle <code>rvss.h</code></li>
</ul>
<aside class="notes">
<p>Wählen Sie den RV32-Single-Cycle-Prozessor, schalten Sie die C-Erweiterung aus und das Extended-Layout ein. Die genauen Menünamen können sich ändern. Ports werden über Namen und Werte identifiziert, nicht über eine geschätzte Mitte des Bildschirms. Manche Steuerungen sind mehrbitige Selektoren. Ein UI-Test dieser Fassung liegt nicht vor. Die Strukturaussage stützt sich auf die genannte Quelldatei.</p>
<p>Kontrollfrage: Liegt die Control immer mittig oben? Das ist nicht belegt. Als Nächstes zählt der angezeigte Wert, nicht nur eine Farbe.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="grüne-vs.-graue-leitungen" class="slide level2">
<h2>Grüne vs.&nbsp;graue Leitungen</h2>
<ul>
<li>Maßgeblich sind Portname, Breite und der angezeigte Wert</li>
<li>Eine 0 kann die richtige MUX-Quelle auswählen</li>
<li><span class="math inline">\(X\)</span> aus der Tabelle ist kein dritter Anzeigewert; 0 und 1 sind bei begründetem Don’t Care beide möglich</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Control --&gt;|1 = High| MUX{MUX schaltet}
  Control --&gt;|0 = Low| Pin[Enable zu]
  style Control fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style MUX fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Pin fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Farben können eine 1 oder 0 unterstützen, ersetzen aber nicht Portname, Breite und Zahl. Eine 0 an einem MUX kann die richtige Quelle wählen und ist dann nicht inaktiv im fachlichen Sinn. X aus der Papiertabelle erscheint nicht als dritte Farbe. Zeigt der Simulator 0 oder 1, sind beide akzeptabel, wenn der Don’t Care begründet ist und keine verbotene Wirkung entsteht.</p>
<p>Kontrollfrage: Muss ein graues Kabel ein Fehler sein? Nein. Eine initialisierte Vorhersage übt die Methode.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="labor-methode-paper-pencil" class="slide level2">
<h2>Labor-Methode: Paper &amp; Pencil</h2>
<ul>
<li>Drei mentale Vorhersagen vor dem Klick</li>
<li>Übung 1 (<code>sub</code>): Wie leuchten <code>RegWrite</code> und <code>MemWrite</code>?</li>
<li><code>RegWrite</code> grün (1) — ALU-Ergebnis speichern</li>
<li><code>MemWrite</code> grau (0) — RAM unberührt</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb21-1"><a aria-label="1"></a>t1 = 9, t2 = 4</span>
<span id="cb21-2"><a aria-label="2"></a>sub t0, t1, t2</span>
<span id="cb21-3"><a aria-label="3"></a># Erwartung im Lehrmodell: t0 = 5</span>
<span id="cb21-4"><a aria-label="4"></a># RegWrite = 1, MemWrite = 0, ALUControl = SUB</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>t1 gleich 9 und t2 gleich 4 sind gesetzte Lehrwerte. sub t0, t1, t2 schreibt 5 nach t0. t0 ist x5, t1 ist x6, t2 ist x7. Vor dem Clock werden Instruktion und stabile Steuerwerte notiert. Erwartet werden RegWrite aktiv, Speicher-Schreibfreigabe inaktiv und die Subtraktion. Die konkreten Ripes-Portcodes werden am Modell abgelesen und nicht aus der Lehrbuchtabelle erfunden. Nach dem Clock ist t0 gleich 5, der Speicher unverändert.</p>
<p>Kontrollfrage: Welcher Wert steht in t0? 5. Ein Load prüft eine andere Write-Back-Quelle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vorhersage-übung-lw" class="slide level2">
<h2>Vorhersage-Übung: <code>lw</code></h2>
<ul>
<li>Übung 2 (<code>lw</code>): Stellung von <code>ALUSrc</code> und <code>MemtoReg</code>?</li>
<li>Beide MUX-Steuerungen auf 1 (grün)</li>
<li><code>ALUSrc = 1</code>: Offset in die ALU</li>
<li><code>MemtoReg = 1</code>: RAM-Daten ins Register</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb22-1"><a aria-label="1"></a># Lehrwerte, nicht ein automatisch vorhandener Simulatorzustand</span>
<span id="cb22-2"><a aria-label="2"></a># zwei Wörter ab Label daten, s1 zeigt darauf</span>
<span id="cb22-3"><a aria-label="3"></a>lw t0, 4(s1)</span>
<span id="cb22-4"><a aria-label="4"></a># Adresse = Basis + 4, MemtoReg wählt den Speicherwert, nicht die Adresse</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Zwei definierte Wörter stehen ab einem Label. s1 wird mit la darauf gesetzt. la kann mehrere echte Befehle erzeugen und ist nicht der Beobachtungsschritt. lw t0, 4(s1) lädt das zweite Wort, dessen Wert von der Adresse verschieden ist. Der Offset 4 ist ein Byteoffset eines ausgerichteten Wortes. Die Vorhersage: Basis plus 4, Load-Zugriff, Speicher-Write-Back, t0 erhält den zweiten Wortinhalt. Den Ripes-Selektor zeigt das Modell.</p>
<p>Kontrollfrage: Ist 4 der Elementindex? Nein, der Byteoffset. Branch verlangt zusätzlich den Kontrollfluss.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vorhersage-übung-bne" class="slide level2">
<h2>Vorhersage-Übung: <code>bne</code></h2>
<ul>
<li>Im Lehrmodell: Branch = 1 und PCSrc = Branch UND NOT Zero</li>
<li>In Ripes nicht als „ALU subtrahiert“ ablesen</li>
<li>Der Vergleich sitzt in einem eigenen Block; das Ziel kann über die ALU laufen</li>
<li>Ein nicht genommener Sprung ist trotzdem eine ausgeführte Branch-Instruktion</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb23-1"><a aria-label="1"></a># Lehrmodell-Erweiterung, kein Ripes-Portwert:</span>
<span id="cb23-2"><a aria-label="2"></a>bne t0, t1, Label</span>
<span id="cb23-3"><a aria-label="3"></a># Branch = 1</span>
<span id="cb23-4"><a aria-label="4"></a># genommen nur bei Ungleichheit</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>bne bedeutet Branch if Not Equal. Im erweiterten Lehrmodell gilt PCSrc gleich Branch und nicht Zero. In Ripes ist das nicht die Beobachtung ALU subtrahiert. Dort vergleicht ein eigener Block, und die Zielberechnung kann über die ALU laufen. Zwei Lehrfälle: gleiche Werte springen nicht, ungleiche schon. Branch bleibt 1, auch wenn der Sprung nicht genommen wird. Register und Label müssen initialisiert sein.</p>
<p>Kontrollfrage: Ist ein nicht genommener bne untätig? Nein, die Bedingung wurde geprüft. Danach folgt eine gedachte falsche Steuerung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fehleranalyse-typo-in-der-matrix" class="slide level2">
<h2>Fehleranalyse: Typo in der Matrix</h2>
<ul>
<li>Gedachte Decoderänderung, kein Fehler, den unverändertes Ripes bei <code>add</code> ausführt</li>
<li>Beispiel: <code>t1 = 0x2000</code>, <code>t2 = 4</code>, falsches <code>MemWrite = 1</code></li>
<li>Adresse <code>0x2004</code> würde mit dem Store-Datenwert 4 beschrieben</li>
<li><code>t0</code> kann trotzdem <code>0x2004</code> erhalten</li>
</ul>
<aside class="notes">
<p>Das Beispiel ist eine gedachte Änderung der Lehrsteuerung, kein Fehler, den normales add in unverändertem Ripes erzeugt. t1 gleich 0x2000 und t2 gleich 4 ergeben die ALU-Adresse 0x2004. Bei falschem MemWrite gleich 1 würde der Speicher an dieser ausgerichteten Adresse den Wert 4 aus rs2 erhalten. t0 kann gleichzeitig 0x2004 bekommen. Die Wirkung ist bestimmt, nicht zufällig. Ein Betriebssystemabsturz oder ein Kurzschluss folgt daraus nicht.</p>
<p>Kontrollfrage: Welcher Speicherwert würde geschrieben? 4. Eine gültige Erweiterung ist addi.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="labor-aufgabe-1-transferleistung" class="slide level2">
<h2>Labor-Aufgabe 1: Transferleistung</h2>
<ul>
<li>Bisher nur reine Basis-Befehle</li>
<li>Aufgabe: Signale für <code>addi</code> (Add Immediate) herleiten</li>
<li>Tipp: liest Konstante (wie <code>lw</code>), speichert ALU-Ergebnis (wie <code>add</code>)</li>
<li>Auf Papier ausfüllen, dann in Ripes an den Kabeln prüfen</li>
</ul>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Instruktion</th>
<th style="text-align: center;">ALUSrc</th>
<th style="text-align: center;">MemtoReg</th>
<th style="text-align: center;">RegWrite</th>
<th style="text-align: center;">MemRead</th>
<th style="text-align: center;">MemWrite</th>
<th style="text-align: center;">Branch</th>
<th style="text-align: center;">ALUOp1</th>
<th style="text-align: center;">ALUOp0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><code>addi</code></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die sichtbare Tabelle bleibt für die Studierenden offen. Die Lösung ist ALUSrc 1, MemtoReg 0, RegWrite 1, MemRead 0, MemWrite 0, Branch 0, ALUOp 00. Der Opcode von addi ist 0010011, funct3 gleich 000. Plus 5 und minus 5 sind beide Additionen. minus 5 wird zu 0xFFFFFFFB. instr[30] ist dabei 1 und wählt keine Subtraktion. andi und ori addieren nicht. Sie brauchen eine andere Detaildecodierung und stehen nicht in dieser einen Zeile.</p>
<p>Kontrollfrage: Welches MemtoReg hat addi? 0. Der Abgleich braucht den richtigen Zeitpunkt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="verifikation-in-ripes" class="slide level2">
<h2>Verifikation in Ripes</h2>
<ul>
<li>Reset, zum markierten Maschinenbefehl gehen</li>
<li>Vor dem Clock: PC und Instruktion notieren, Steuerwerte lesen</li>
<li>Genau einen Clock ausführen, danach Register, Speicher und PC prüfen</li>
<li>Nach dem Clock können die Leitungen schon zur nächsten Instruktion gehören</li>
<li>Single Cycle hat keine eigene Control-Phase</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb24-1"><a aria-label="1"></a>Gruenes Kabel am ALUSrc-MUX  -&gt; 1 in der Tabelle</span>
<span id="cb24-2"><a aria-label="2"></a>Graues Kabel                 -&gt; 0 in der Tabelle</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Single Cycle hat keine Pipeline-Control-Phase. Zuerst zurücksetzen und initialisieren. Vor dem Clock den PC und die Maschineninstruktion notieren und die stabilen Portwerte lesen. Dann genau einen Clock ausführen und Register, Speicher sowie den nächsten PC prüfen. Danach können die Leitungen schon zur folgenden Instruktion gehören. Bei Pseudoinstruktionen zählt das Disassembly, nicht jede Quelltextzeile als ein Befehl.</p>
<p>Kontrollfrage: Dürfen Sie die Steuerwerte nach dem Clock noch dem abgeschlossenen Befehl zuordnen? Nicht ohne Prüfung. Das Programm übt mehrere Write-Back-Quellen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="labor-aufgabe-2-der-mux-beobachter" class="slide level2">
<h2>Labor-Aufgabe 2: Der MUX-Beobachter</h2>
<ul>
<li>Vollständiges Programm in <code>beispiele/vl6_mux_beobachter.s</code></li>
<li>Initialisierung, Store, Load und zwei <code>beq</code>-Ausgänge</li>
<li>Am Prüfpunkt: <code>t0 = 5</code>, <code>t1 = 10</code>, <code>t2 = 10</code>, <code>t3 = 1</code>, Speicherwort = 10</li>
<li><code>$X$</code> nur in der Papiertabelle; der Simulator zeigt einen konkreten Wert</li>
<li>Abschluss in Ripes: Dienst 10 in <code>a7</code>, dann <code>ecall</code></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb25-1"><a aria-label="1"></a>Fokus auf ein einziges Bauteil hilft gegen</span>
<span id="cb25-2"><a aria-label="2"></a>Reizueberflutung im Diagramm.</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Das Programm in beispiele/vl6_mux_beobachter.s initialisiert slot mit einem Wort 0. la s1, slot setzt den Zeiger. la kann mehrere Instruktionen sein. Danach: addi t0, x0, 5 schreibt 5. add t1, t0, t0 schreibt 10. sw t1, 0(s1) schreibt 10 in den Speicher, MemtoReg ist X. lw t2, 0(s1) lädt 10, MemtoReg ist 1. beq t0, t1 springt nicht, weil 5 ungleich 10 ist. addi t3, x0, 1 schreibt 1. beq t1, t2 springt, weil beide 10 sind, und überspringt addi t3, x0, 99. Am Prüfpunkt gelten t0 gleich 5, t1 gleich 10, t2 gleich 10, t3 gleich 1 und das Speicherwort 10. Die konkreten PC-Adressen kommen aus dem Disassembly, nicht aus einer erfundenen Startadresse. Der Ripes-Abschluss setzt a7 auf 10 und führt ecall aus. Das ist die Ripes-Konvention, nicht der Venus-Dienst in a0. la und ecall liegen außerhalb der sieben-Signal-Matrix.</p>
<p>Kontrollfrage: Welchen Wert hat t3, wenn der zweite beq genommen wird? 1. Die Schlussfolie bündelt die Prüfung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="qa-und-hands-on" class="slide level2">
<h2>Q&amp;A und Hands-On</h2>
<ul>
<li>Ripes starten</li>
<li>Meistertabelle als Kompass nutzen</li>
<li>Unerwartetes Verhalten: Logik der Hardware ergründen</li>
<li>Viel Erfolg bei der Entschlüsselung des Steuerwerks</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="3.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B', 'secondaryColor': '#F5F5F7', 'tertiaryColor': '#FFFFFF', 'mainBkg': '#FFFFFF', 'nodeBorder': '#E5E5EA', 'clusterBkg': '#F5F5F7', 'clusterBorder': '#E5E5EA', 'titleColor': '#1D1D1F', 'edgeLabelBackground': '#FFFFFF'}}}%%

graph LR
  Theorie[Matrix] --&gt;|Wissen| Labor[Ripes]
  Labor --&gt;|Clock| Analyse[Signale prüfen]
  Analyse --&gt; Win[Verstaendnis]
  style Win fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
  style Theorie fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Labor fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
  style Analyse fill:#FFFFFF,stroke:#E5E5EA,stroke-width:1.5px
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Q&amp;A bedeutet Questions and Answers, Hands-On die praktische Übung. Der Weg ist Befehlsfeld, Decoder, Auswahl oder Freigabe, berechneter Wert, Zustandsänderung. Fünf Kurzantworten: Es sind sieben Signale und acht Bits. MemtoReg ist bei sw ein X, weil RegWrite 0 ist. Branch ist die Freigabe, PCSrc die fertige Auswahl. addi mit minus 5 addiert trotz Bit 30 gleich 1. Der Ripes-Branch vergleicht in einem eigenen Block, das Lehrmodell nutzt ALU-SUB. Einheit 7 behandelt Pipelining. Dort werden Execute, Memory und Write Back auf mehrere Takte verteilt. Zusätzliche Steuerfragen entstehen. Diese Folie behauptet nicht, jene Einheit schon ausgeführt zu haben.</p>
<p>Kontrollfrage: Ist PCSrc ein achter Main-Control-Ausgang? Nein. Damit ist das Lehrsubset steuerbar und vom Simulator unterscheidbar.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../assets/dhbw_logo.svg" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    /**
     * Fit Quarto/Reveal Mermaid SVGs to remaining slide space.
     * Dimensions from getBoundingClientRect are viewport pixels; CSS sizes inside
     * Reveal slides are unscaled — divide by Reveal.getScale().
     */
    (function () {
      const BOTTOM_PAD = 36;
      const SIDE_PAD_RATIO = 0.92;
      const MAX_SCALE = 3.4;

      function presentSlide() {
        var present = document.querySelector("section.present");
        if (!present) return null;
        var nested = present.querySelector(":scope > section.present");
        return nested || present;
      }

      function revealScale() {
        if (window.Reveal && typeof Reveal.getScale === "function") {
          var s = Reveal.getScale();
          return s > 0.05 ? s : 1;
        }
        return 1;
      }

      function ensureWrap(svg) {
        var parent = svg.parentElement;
        if (!parent) return null;
        if (parent.classList.contains("mermaid-fit")) return parent;
        var wrap = document.createElement("div");
        wrap.className = "mermaid-fit";
        parent.insertBefore(wrap, svg);
        wrap.appendChild(svg);
        return wrap;
      }

      function contentBottomAbove(slide, wrap) {
        var top = slide.getBoundingClientRect().top;
        var bottom = top + 8;
        var children = slide.children;
        for (var i = 0; i < children.length; i++) {
          var el = children[i];
          if (el === wrap || el.classList.contains("mermaid-fit")) break;
          if (el.querySelector && el.querySelector("svg.mermaid-js")) break;
          if (el.tagName === "ASIDE") continue;
          var r = el.getBoundingClientRect();
          if (r.height > 1) bottom = Math.max(bottom, r.bottom);
        }
        return bottom;
      }

      function naturalSize(svg) {
        if (svg.dataset.natW && svg.dataset.natH) {
          return { w: +svg.dataset.natW, h: +svg.dataset.natH };
        }
        var vb = svg.viewBox && svg.viewBox.baseVal;
        if (vb && vb.width > 0 && vb.height > 0) {
          svg.dataset.natW = String(vb.width);
          svg.dataset.natH = String(vb.height);
          return { w: vb.width, h: vb.height };
        }
        var wAttr = parseFloat(svg.getAttribute("width"));
        var hAttr = parseFloat(svg.getAttribute("height"));
        if (wAttr > 0 && hAttr > 0) {
          svg.dataset.natW = String(wAttr);
          svg.dataset.natH = String(hAttr);
          return { w: wAttr, h: hAttr };
        }
        var r = svg.getBoundingClientRect();
        var rs = revealScale();
        var w = r.width / rs || 320;
        var h = r.height / rs || 120;
        svg.dataset.natW = String(w);
        svg.dataset.natH = String(h);
        return { w: w, h: h };
      }

      function fitMermaids() {
        var slide = presentSlide();
        if (!slide) return;

        var rs = revealScale();
        var slideRect = slide.getBoundingClientRect();
        var svgs = slide.querySelectorAll("svg.mermaid-js");

        for (var i = 0; i < svgs.length; i++) {
          var svg = svgs[i];
          var wrap = ensureWrap(svg);
          if (!wrap) continue;

          svg.style.removeProperty("transform");
          svg.style.removeProperty("max-width");
          svg.style.removeProperty("zoom");
          wrap.style.zoom = "";

          var nat = naturalSize(svg);
          var above = contentBottomAbove(slide, wrap);
          var availW = (slideRect.width * SIDE_PAD_RATIO) / rs;
          var availH = Math.max(72, (slideRect.bottom - above - BOTTOM_PAD) / rs);

          var scale = Math.min(availW / nat.w, availH / nat.h, MAX_SCALE);
          if (!(scale > 0)) scale = 1;

          var targetW = Math.max(1, Math.round(nat.w * scale));
          var targetH = Math.max(1, Math.round(nat.h * scale));

          svg.setAttribute("width", targetW);
          svg.setAttribute("height", targetH);
          svg.style.width = targetW + "px";
          svg.style.height = targetH + "px";
          svg.style.display = "block";
          svg.style.margin = "0.35rem auto 0";
        }
      }

      function scheduleFit() {
        requestAnimationFrame(function () {
          fitMermaids();
          setTimeout(fitMermaids, 150);
          setTimeout(fitMermaids, 500);
          setTimeout(fitMermaids, 1100);
        });
      }

      window.addEventListener("load", scheduleFit);

      function bindReveal() {
        if (!window.Reveal || !Reveal.on) return false;
        Reveal.on("ready", scheduleFit);
        Reveal.on("slidechanged", scheduleFit);
        if (Reveal.isReady && Reveal.isReady()) scheduleFit();
        return true;
      }

      if (!bindReveal()) {
        window.addEventListener("load", function () {
          var tries = 0;
          var id = setInterval(function () {
            if (bindReveal() || ++tries > 50) clearInterval(id);
          }, 100);
        });
      }

      window.mctMermaidFit = fitMermaids;
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Kopiert");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Kopiert");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dantschi\.github\.io\/mct1\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>